////
|metadata|
{
    "name": "about-ajax-compression",
    "controlName": [],
    "tags": ["Performance"],
    "guid": "{8F7E38E9-0A9E-4BFD-A605-3E89653E20B2}",
    "buildFlags": [],
    "createdOn": "2010-09-03T16:53:49Z"
}
|metadata|
////

= Ajax 圧縮について

{ProductName} 10.1 の新しい AJAX 圧縮モジュールは、{ProductName} AJAX フレームワークに基づいて {ProductName} AJAX コントロールを使用するときにサーバーで生成された Ajax レスポンスを圧縮します。ブラウザーは、クライアント側でレスポンスを展開してからその後の処理をします。

この機能をオンにした場合、以下のベネフィットがあります。

* *帯域幅* - レスポンスが GZIP されたの場合、Ajax によって使用される帯域幅は自動的に減少します。帯域幅の容量が向上し、同じ時間でより多くのユーザーをネットワークに支障をきたすことなくサポートできます。
* *スピード* - レスポンス サイズが減少した場合、サーバーからの Ajax リクエストのラウンドトリップが減少します。

以下のテーブルは、26 列、2155 行あるページングが有効な WebDataGrid コントロールを使用した場合の AJAX 圧縮を取得するパフォーマンスを示します。

=== 圧縮なし

[options="header", cols="a,a,a"]
|====

|WebDataGrid ページ サイズ|レスポンス (KB)|ラウンドトリップ タイム (秒)

|20
|50.6
|1.18

|50
|81.1
|1.14

|100
|140.9
|1.23

|200
|261.8
|1.4

|500
|627.7
|2.13

|1000
|1228.8
|4.32

|====

=== 圧縮あり

[options="header", cols="a,a,a"]
|====

|WebDataGrid ページ サイズ|レスポンス (KB)|ラウンドトリップ タイム (秒)

|20
|7.4
|1.19

|50
|10.2
|1.19

|100
|15.8
|1.19

|200
|27.4
|1.29

|500
|62.5
|1.51

|1000
|121
|2.12

|====

AJAX 圧縮が有効な場合、web.config に以下の HTTP モジュールを追加してください。{ProductName} AJAX ベース コントロールのすべての Ajax レスポンスが圧縮されます。これによって、前途のようなベネフィットがあります。

以下のコードは、AJAX 圧縮を有効にする方法を示します。

*HTML の場合:*

----
<httpModules>
        ...
        <add name="Compression" type="Infragistics.Web.UI.Framework.Compression, Infragistics4.Web.v10.1, Version=10.1.20101.85, Culture=neutral, PublicKeyToken=7dd5c3163f2cd0cb"/>
</httpModules>
----