////

|metadata|
{
    "name": "aspnet-versionless-assemblies",
    "controlName": [],
    "tags": ["API","Application Scenarios","How Do I"],
    "guid": "a0c2d737-4756-4924-a58a-44f89b114218",  
    "buildFlags": [],
    "createdOn": "2010-10-07T07:12:19.9589688Z"
}
|metadata|
////

= Version-less アセンブリ

== 始める前に

{ProductName}™ ツールセットでビルドされた ASP.NET アプリケーションでは、バージョンの競合を回避するために、これまでファイル名にバージョン番号が組み込まれているアセンブリを使用してきました。バージョンの安全性は多くの状況で貴重ですが、新しいバージョン番号を反映するために構成ファイルを更新することなく、新しいバージョンのツールセットをアプリケーションにドロップできるようにしたい場合があります。

== Version-less アセンブリはどのランタイムに対してコンパイルされるのか?

インフラジスティックスは多数の異なるランタイムに対してコンパイルされた {ProductName} を出荷していますが、Version-less アセンブリ名を持つ DLL は常に最新バージョンの ASP.NET ランタイムに対してコンパイルされます。

== 達成すること

既存の ASP.NET アプリケーションを取得して、Version-less アセンブリ名を持つ DLL に対して実行するために参照および構成情報を更新する方法を学習します。

== 次の手順を実行します。

最初に、普通のバージョンが設定されたアセンブリを使用して通常通りにアプリケーションを作成します。

アプリケーションをパブリッシュする準備が整ったら、バージョンが設定されたアセンブリ名を持つ DLL への参照を削除して、Version-less アセンブリへの参照を追加します。Version-less DLL をアプリケーションの bin フォルダに配置するか、GAC に配置できます。

次に、アプリケーションの [参照] ダイアログでバージョンが設定された DLL への参照を削除して、Version-less アセンブリへの参照を追加することによって、Version-less アセンブリ名を使用して、コントロール DLL を参照するようにアプリケーションを更新する必要があります。

Version-less アセンブリ名を持つ DLL への参照を設定する時には、必ず SpecificVersion を False に、CopyLocal を True に設定するように References プロパティを構成します。

アプリケーションが希望する場所にパブリッシュされたら、Web.config ファイルを開いて、アセンブリ参照を編集します。

*注:* コントロール参照を Web.config ファイルに移動するように推奨します。これは、アプリケーションのコントロールへのアクセスを集中化する支援となります。そうでない場合には、すべての .aspx ファイルまたは .ascx ファイルでバージョン情報を変更する必要があります。


以下の例は、バージョンが設定されたアセンブリ名を持つ DLL を参照する Web.config ファイルでのエントリを示します。

[cols="a"]
|====
|Web.config で:

|   

< tagPrefix="ig"> 

namespace="Infragistics.Web.UI.GridControls" 

assembly="Infragistics4.Web.v10.3, Version=10.3.20103.100, Culture=neutral, PublicKeyToken=7DD5C3163F2CD0CB" />       

...  

|====

アプリケーションが Version-less アセンブリにアクセスできるようにするためには、以下に示すようにアセンブリ参照からバージョン番号を削除する必要があります。

[cols="a"]
|====
|Web.config で:

|   

< tagPrefix="ig"> 

namespace="Infragistics.Web.UI.GridControls" 

assembly="Infragistics.Web" />       

...  

|====

*注:* .licx ファイルでもバージョン情報を変更しなければならない場合があります。


Web.config ファイルからバージョン情報を削除し、アプリケーションが Version-less アセンブリを参照するようにすることにより、アプリケーションは非依存の Infragistics コントロール バージョン番号を実行することができます。

== アプリケーション メンテナンス

2010.3 リリース時点で、Version-less アセンブリはアプリケーションを実行するために DLL しかサポートしていません。Visual Studio™ でアプリケーションを開く必要がある場合、デザイナーのサポートを取得するためには、バージョンが設定されたアセンブリ名を使用するようにアプリケーションを戻す必要があります。アプリケーションへの更新が完了したら、パブリッシュする前に再度 Version-less アセンブリ名を使用するようにアプリケーションを構成することができます。