////

|metadata|
{
    "name": "persistenceframework-api-overview",
    "controlName": ["PersistenceFramework"],
    "tags": ["API","Persistence"],
    "guid": "89304c00-e244-4f7a-ba0c-57f65f12cf2e",  
    "buildFlags": [],
    "createdOn": "2011-05-31T14:41:06.2907675Z"
}
|metadata|
////

= API の概要

このセクションではフレームワークに関連する各名前空間を示します。このフレームワーでプログラムする間に使用するいくつかのキー クラスも提供します。このページの名前空間とクラスは当社の API マニュアルに直接リンクします。

=== PersistenceFramework 名前空間:

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence_namespace.html[Infragistics.Web.UI.Framework.Persistence]"]

=== キー クラス:

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.apppersistencemanager.html[AppPersistenceManager]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.controldata.html[ControlData]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.persistencedata.html[PersistenceData]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.persistencemanager.html[PersistenceManager]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.persistence.propertydata.html[PropertyData]"]