////

|metadata|
{
    "name": "web-webdatatree",
    "controlName": ["WebDataTree"],
    "tags": [],
    "guid": "{279A6945-027C-4C68-8AE3-C38BCC2FC196}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebDataTree

このページには、WebDataTree™ コントロール関連の概要/タスクベースの情報がすべて含まれています。このセクションには、コントロールが何を実行するのか、またアプリケーションでなぜコントロールを使用したくなるのかから、コントロールを使用して一般的なタスクを完了する方法に関するステップバイステップの手順まで、コントロールに関する貴重な情報が含まれています。

WebDataTree コントロールについての詳細は、以下のリンクをクリックしてください。

== link:webdatatree-about-webdatatree.html[WebDataTree について]

このセクションには、WebDataTree コントロールの機能の理解を深めるのに役立つ情報があります。さらに、コントロールの目的も理解できます。

== link:webdatatree-getting-started-with-webdatatree.html[WebDataTree で開始]

このセクションは、WebDataTree コントロールで可能な限り迅速に起動および実行する方法についての情報を提供します。

== link:webdatatree-using-webdatatree.html[WebDataTree の使用]

このセクションは、WebDataTree で使用可能な機能を使用する方法を示すタスクベースの情報を提供します。

== link:webdatatree-accessibility-compliance.html[WebDataTree アクセシビリティの遵守]

このトピックは、WebDataTree が第 508 条の要件を満たす方法を概略します。このアクセシビリティの遵守によって、エンドユーザー、特に障害を持つユーザーが WebDataTree コントロールを使用して構築された Web アプリケーションにアクセスおよび使用することを可能にします。

== link:webdatatree-api-overview.html[API の概要]

このトピックは、WebDataTree コントロールでプログラミング中に作業する名前空間とクラスをリストします。このトピックにリストされている名前空間とクラスは、{ProductName} ヘルプの「API 参照ガイド」セクションに便宜的にリンクされています。

== link:webdatatree~infragistics.web.ui_namespace.html[クライアント サイド オブジェクト モデル (CSOM) の概要]

WebDataTree™ コントロールは、クライアント側の JavaScript プログラミング環境に堅牢なオブジェクト モデルを提供します。オブジェクト モデルは、十分な機能を備えた JavaScript オブジェクトで構成され、開発者はサーバー側にポストバックしなくても、コントロールに関連する重要な機能単位をプログラムできます。