////

|metadata|
{
    "name": "web-whats-new-in-2009-volume-1",
    "controlName": [],
    "tags": ["FAQ","Getting Started"],
    "guid": "{F402E079-849E-494B-BCA3-F51FB44F1681}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 2009 Volume 1 の新機能

{ProductName} 2009 Volume 1 リリースは新しい Infragistics ドラッグ アンド ドロップ フレームワーク とともに {ProductName} AJAX フレームワークに構築された新しいコントロールのコレクションを含みます。

== 新しいドラッグ アンド ドロップ フレームワーク

ドラッグ アンド ドロップ フレームワーク™ によってドラッグ アンド ドロップ機能をアプリケーションに簡単に追加できます。これによって要素のリアルタイムの移動とよりユーザー フレンドリーな操作が可能になります。フレームワークはドラッグアンドドロッププロセスを処理するだけでなくカスタムなアニメーションを作成するために必要なスクリプトを提供します。

ドラッグ アンド ドロップ フレームワークの機能の一部は以下のとおりです:

* *実装が容易* - このフレームワークはドラッグ アンド ドロップ機能の追加を可能な限り簡単にするために必要なピースを提供します。
* *拡張およびカスタマイズ可能* - ほとんどすべての要素は固有のドラッグ アンド ドロップ マークアップを提供するための機能によってドラッグ可能です。
* *カスタム アニメーション* - カスタム アニメーションの追加機能によって円滑かつ高度なドラッグ アンド ドロップ動作が可能となります。

== 関連トピック

link:draganddropframework-about-drag-and-drop-framework.html[ドラッグ アンド ドロップ フレームワークについて]

link:draganddropframework-getting-started-with-drag-and-drop.html[ドラッグ アンド ドロップで開始]

link:draganddropframework-using-drag-and-drop-framework.html[Drag and Drop Framework の使用]

== 新しい WebDataMenu コントロール

WebDataMenu™ コントロールは {ProductName} AJAX コントロールの広範なリストへの新たな追加です。WebDataMenu の新しいデザインでは、ネーティブの AJAX 機能によって効率的で拡張性の高いマルチレベルの階層的なメニュー、またはポップアップコンテキストメニューコントロールとなっています。

すべての {ProductName} AJAX コントロールのように、WebDataMenu は Infragistics® Application Styling Framework にシームレスに統合します。CSS ベースのプロパティを使用すると、既存のスタイルシートを利用することによって、WebDataMenu コントロールを手動でカスタマイズできます。

WebDataMenu の機能のいくつかは以下の通りです。

* *ハイパフォーマンス* - 軽量のマークアップと最適化されたコードがパフォーマンスを向上します。
* *標準への適合* - CSS 2 および XHTML 1.0 に準拠します。
* *多数のデータ ソースをサポート* - IEnumerable を実装している 標準的な Microsoft データ ソース コントロールおよびオブジェクトを含み、広範なバインド可能なデータ ソースをサポートします。メニュー レイアウトを動的に定義するためにフラットなデータ モデルだけでなく階層的なデータ モデルでさえ WebDataMenu にバインドできます。
* *テンプレート* - 複雑なカスタム レイアウトを実現し究極的な柔軟性を取得できるように WebDataMenu 項目をテンプレート化できます。
* *クライアント サイド オブジェクト モデル* - クライアント側でのコールバックの実行を不要にすることができるクライアント側イベントを処理します。
* *メニューの方向* - WebDataMenu は垂直、水平の方向に設定することができ、両方の方向を同時に含むことさえ可能です。
* *ポップアップ コンテキスト メニュー* - WebDataMenu はポップアップ コンテキスト メニューとなるように構成できます。エンドユーザーは Page コントロールを右クリックして関連付けられたタスクでポップアップ メニューを起動することができます。
* *メニュー項目の状態* - WebDataMenu 項目は Selected、Active、Hovered さらには Disabled といったさまざまな状態をサポートします。各状態は区別してスタイルできます。
* *ネーティブの AJAX サポート* - {ProductName} AJAX コントロールは Microsoft® ASP.NET AJAX Extensions 上に構築されているので、ほとんどの WebDataMenu の機能は AJAX を使用して実行されます。これによりフル ページ ポストバックを排除します。

== 関連トピック

link:webdatamenu-about-webdatamenu.html[WebDataMenu について]

link:webdatamenu-getting-started-with-webdatamenu.html[WebDataMenu で開始]

link:webdatamenu-using-webdatamenu.html[WebDataMenu の使用]

== 新しい WebDataTree コントロール

WebDataTree™ コントロールは {ProductName} AJAX コントロールの広範なリストへの新たな追加です。WebDataTree の新しいデザインによって、効率的で拡張性の高いマルチレベルの階層的なツリー コントロールとなっています。WebDataTree は階層的なデータモデルを表示するために使用することも可能ですが、ナビゲーション コントロールとして使用することも可能です。WebDataTree をアプリケーションに統合するときに多くの可能性が存在します。

すべての {ProductName} AJAX コントロールのように、WebDataTree は Infragistics® Application Styling Framework にシームレスに統合します。CSS ベースのプロパティを使用すると、既存のスタイルシートを利用することによって、WebDataTree コントロールを手動でカスタマイズできます。

WebDataTree の機能のいくつかは以下の通りです。

* *ハイパフォーマンス* - 軽量のマークアップと最適化されたコードがパフォーマンスを向上します。
* *標準への適合* - CSS 2 および XHTML 1.0 に準拠します。
* *ロード オン デマンド* - 初期のページ ロード時にデータ ソース全体を最初にレンダリングするのではなく、初期のページ ロード時に少量のデータのみを送信するロード オン デマンド機能を有効にすることができます。後続のノード拡張は AJAX コールバックを起動し、これにより追加のノードが取得およびロードされます。これは 1 回の試行で大きいデータ ソース全体をロードすることよりも劇的なパフォーマンスの改善を提供します。
* *テンプレート* - 究極的な柔軟性のために WebDataTree 要素をテンプレート化できます。ノードをテンプレート化することもでき、WebDataTree でデータがロードされない時のためにテンプレートを提供することも可能です。
* *ノードの編集* - WebDataTree ノードを編集することも可能です。エンドユーザーはダブルクリックするか F2 を押して特定のノードで編集モードを起動できます。
* *アニメーション* - WebDataTree ノード拡張はアニメートして発生できます。プロフェッショナルのアニメーション効果を Web アプリケーションに簡単に追加することができるように、シンプルなプロパティ設定を介して多くのプリセット アニメーション オプションが公開されています。
* *クライアント サイド オブジェクト モデル* - WebDataTree は、サーバー側のラウンド トリップを伝統的に必要とする多くのイベントに応答するために処理可能なプロパティ、メソッド、さらにはイベントさえ公開する広範なクライアント サイド オブジェクト モデルを提供します。このタイプのアーキテクチャは、アプリケーションで使用されると非常に高速で対応に優れたエンドユーザー エクスペリエンスを促進します。
* *その他に多数機能があります!*

== 関連トピック

link:webdatatree-about-webdatatree.html[WebDataTree について]

link:webdatatree-getting-started-with-webdatatree.html[WebDataTree で開始]

link:webdatatree-using-webdatatree.html[WebDataTree の使用]

== 新しい WebDropDown コントロール

WebDropDown™ コントロールは {ProductName} AJAX コントロールの広範なリストへの新たな追加です。WebDropDown の新しいデザインによってネーティブの AJAX 機能を使用して効率的で拡張性の高いリスト コントロールとなっています。

すべての {ProductName} AJAX コントロールのように、WebDropDown は Infragistics® Application Styling Framework にシームレスに統合します。CSS ベースのプロパティを使用すると、既存のスタイルシートを利用することによって、WebDropDown コントロールを手動でカスタマイズできます。

WebDropDown の機能のいくつかは以下の通りです。

* *ハイパフォーマンス* - 軽量のマークアップと最適化されたコードがパフォーマンスを向上します。
* *標準への適合* - CSS 2 および XHTML 1.0 に準拠します。
* *多数のデータ ソースをサポート* - IEnumerable を実装している 標準的な Microsoft データ ソース コントロールおよびオブジェクトを含み、広範なバインド可能なデータ ソースをサポートします。
* *複数の項目選択* - エンドユーザーはドロップダウン リストから複数項目を選択できます。
* *ロード オン デマンド* - 1 回のトリップでデータ ソース全体をクライアントに送信するのではなく、ロード オン デマンドを有効にすることができます。この場合最初に少量のデータを送信します。これによりページを描画するためにかかる時間を削減します。エンドユーザーが項目のリストをスクロールすると、素早く応答性に優れたエンドユーザー エクスペリエンスのためにクライアントに存在しない項目は非同期にフェッチされシーンの背後でロードされます。
* *ページング* - データを複数ページに分割することでパフォーマンスを向上します。WebDataGrid™ および WebGrid でのページングと同様に、大きいデータ ソースは一度にすべてではなく小さいセグメントでクライアントに送信されます。エンドユーザーはナビゲートしたいページ番号をクリックするだけです。
* *オート コンプリート* - エンドユーザーは WebDropDown Text エディターに入力し、ドロップダウン リストで最初の一致項目にスクロールされます。これは大きい項目のリストがあるときには必ずエンドユーザー エクスペリエンスを向上します。
* *オート フィルタリング* - エンドユーザーが WebDropDown Text エディタに入力して、ドロップダウン リストに示されるそのテキストで開始する一致を提案します。これは大きい項目のリストからデータを選択する必要があるときには常にエンドユーザー エクスペリエンスを大幅に向上するもうひとつの機能です。
* *キーボード ナビゲーション* - WebDropDown はキーボード ナビゲーションの完全なセットをサポートします。この場合エンドユーザーはシンプルなキーボードストロークを介して多くのタスクを実行できます。アプリケーションがキーボード ナビゲーションを許可する時には常にエンドユーザーのデータ入力および選択は大幅に改善されます。
* *テンプレート* - リスト項目をテンプレート化して最大の柔軟性とカスタマイズ化を可能にすることができます。リスト項目をより魅力的で役立つようにするグラフィックス、カスタム コントロールおよびその他のオブジェクトで項目リストをカスタマイズすることを想像してください。
* *ネーティブの AJAX サポート* - {ProductName} AJAX コントロールは Microsoft® ASP.NET AJAX Extensions 上に構築されているので、ほとんどの WebDropDown の機能は AJAX を使用して実行されます。これによりフル ページ ポストバックを排除します。

== 関連トピック

link:webdropdown-about-webdropdown.html[WebDropDown について]

link:webdropdown-getting-started-with-webdropdown.html[WebDropDown で開始]

link:webdropdown-using-webdropdown.html[WebDropDown の使用]

== 新しい WebProgressBar コントロール

WebProgressBar™ コントロールは {ProductName} AJAX コントロールの広範なリストへの新たな追加です。WebProgressBar の新しいデザインによって効率的で拡張性の高い進行状況インジケータ コントロールとなっています。WebProgressBar を使用して、現在の操作の進行状況を更新してエンドユーザーに示すだけでなく、AJAX が現在進行中であることを示す視覚的なアニメートしたキューを提供することができます。

すべての {ProductName} AJAX コントロールのように、WebProgressBar は Infragistics® Application Styling Framework にシームレスに統合します。CSS ベースのプロパティを使用すると、既存のスタイルシートを利用することによって、WebProgressBar コントロールを手動でカスタマイズできます。

WebProgressBar の機能のいくつかは以下の通りです。

* *ハイパフォーマンス* - 軽量のマークアップと最適化されたコードがパフォーマンスを向上します。
* *標準への適合* - CSS 2 および XHTML 1.0 に準拠します。
* *アニメーション* - WebProgressBar 値はアニメートして発生できます。プロフェッショナルの進行状況表示を Web アプリケーションに簡単に追加することができるように、シンプルなプロパティ設定を介して多くのプリセット アニメーション オプションが公開されています。
* *方向* - 垂直および水平進行状況表示によってさまざまなユーザー インタフェース構成が可能となります。
* *クライアント サイド オブジェクト モデル* - WebProgressBar は基本的にクライアント側指向のコントロールで、JavaScript を使用してそれ以外の方法ではサーバー側コールバックを必要とするイベントを操作および応答することができます。このアーキテクチャによってそれ以外の方法ではフル ページ ポストバックによって妨害される素早く応答性に優れたユーザー インタフェースを作成することが可能となります。

== 関連トピック

link:webprogressbar-about-webprogressbar.html[WebProgressBar について]

link:webprogressbar-getting-started-with-webprogressbar.html[WebProgressBar で開始]

link:webprogressbar-using-webprogressbar.html[WebProgressBar の使用]

== 新しい WebDataGrid の列の移動

WebDataGrid™ コントロールは列の移動をサポートするようになりました。エンドユーザーは列ヘッダーをクリック アンド ドラッグして位置を変更可能になりました。これは、提示されている順序から表示可能な列の配置を変更したいエンドユーザーに役立ちます。

列の移動は操作の間列ヘッダーのドラッグ方法の構成を可能にするいくつかの UI 拡張も提供されています。列ヘッダーはドラッグの間エンドユーザーのマウスポインターの後を付いていくことができ、この間同時に半透明の状態にフェードします。または列ヘッダーはエンドユーザーが列をドラッグする間にヘッダーの残りとこれまでどおりにインラインのままにすることができます。

== 関連トピック

link:webdatagrid-column-moving.html[列の移動]

== その他

== Chrome のサポート

* すべての ASP.NET AJAX コントロールが Chrome でサポートされるようになりました。
* WebSchedule™ は Chrome で今回サポートされます。

== Application Styling Framework™

* すべての ASP.NET コントロールに対して単一のアプリケーション スタイル設定を適用できるようになりました。
* コード内からスタイルを作成するための CSS レジストリ