////

|metadata|
{
    "name": "web-upgrading-web-applications-to-make-use-of-application-styling",
    "controlName": [],
    "tags": ["Styling","Tips and Tricks"],
    "guid": "{62A91E74-ECB0-4BBF-9942-384FAD9EE3D1}",  
    "buildFlags": [],
    "createdOn": "2007-09-02T13:49:17Z"
}
|metadata|
////

= Web アプリケーションをアップグレードしてアプリケーション スタイリングを使用可能にする

2007 Volume 1 リリースからから開始しましたが、アプリケーション スタイリングが {ProductName} 製品で使用可能となりました。

{ProductName} コントロールでアプリケーション スタイリングを実行するための方法は 2 通りあります。

* 既存のアプリケーション内で、新しいアプリケーションと新しいフォームのアプリケーション スタイリングをオンにします。
* 現在使用しているスタイル値の代わりにスタイルセットのスタイルおよび外観を採用するように既存のアプリケーションを変更します。

== 既存のアプリケーション内で、新しいアプリケーションおよびフォームのアプリケーション スタイリングをオンにする

{ProductName} コントロールとアプリケーションスタイリングを使用する最も簡単な方法は、既存のアプリケーション内で新しいアプリケーションと新しいフォームのためのアプリケーションスタイリングをオンにすることです。このアプローチを使用すると、既存のフォームおよびアプリケーションのスタイル設定がそのままで変更が不要です。一方、既存のアプリケーションに追加された新しいフォームは、 link:web-webpagestyler.html[WebPageStyler] コンポーネントを使用することで、アプリケーション スタイリングをオンにすることができます。

アプリケーション全体のアプリケーション スタイリングをオンにするには、Microsoft® Visual Studio のツール メニューからアクセス可能な Infragistics Application Styling Configuration ツールを使用します。

特定のページまたは新しいフォームに対してアプリケーション スタイリングをオンにするには、Infragistics4.WebUI.Misc アセンブリに含まれている WebPageStyler コンポーネントを使用します。WebPageStyler コンポーネントには以下を実行できるプロパティが含まれています。

* アプリケーション スタイリングを有効にする
* StyleSetName を指定する
* StyleSetPath 値を指定する

個々のコントロールと一緒にこれらの技術を使用すると、アプリケーション スタイリングをアプリケーション、ページ、またはコントロールのレベルで有効または無効にできます。

== スタイルセットのスタイルおよび外観を採用するために既存のアプリケーションを変更する

{ProductName} コントロールとアプリケーション スタイリングを使用するためのもうひとつのアプローチは、現在使用しているスタイル値の代わりにスタイルセットのスタイルおよび外観を採用するように既存のスタイルを変更することです。

この場合、スタイルセットのスタイル設定が優先順位で実行されるためにはアプリケーションのスタイル設定を削除する必要があります。一定のスタイルの CSS ファイルにある CSS スタイル規則および値は、アプリケーションのスタイルオブジェクトで相当する規則と異なる値を設定することで簡単に無効にできます。アプリケーション スタイリングが以前にスタイルしたページで有効な場合、これは通常状況となります。

アプリケーション スタイリング値がスタイルセットから来るを確認するための鍵は、スタイルセット値を無効にしないようにアプリケーションに設定されている適切なスタイル値を削除することです。個々のアプリケーションおよびスタイル値が異なるため、自分の裁量でこのタスクを実行しなければなりません。

フォームにドロップしたときに適切に WebGrid および WebCombo コントロールが表示するために、これらのコントロールをデフォルトに設定することを考慮する場合、Reset Default Styles コマンドを使用してデフォルトのスタイルをクリアすることができます。このコマンドはコントロールのショートカット メニューで見つかります。

その他のスタイルおよびコントロールについては、アプリケーション スタイリングの設定を無効にするスタイル値を削除するために ASPX ページを直接編集する、またはデザイン画面で Style オブジェクトを編集することができます。

繰り返しになりますが、アプリケーション スタイリングを活用するように既存のアプリケーションを更新する場合、アプリケーション全体がアプリケーション スタイリングに有効かどうかに関しては非常な柔軟性があります。1 ページまたは数ページだけをアプリケーションスタイリングに有効にすることもできます。またはコントロールの [アプリケーション スタイリングを有効にする] プロパティを使用することで特定のページのひとつまたは複数のコンポーネントだけをアプリケーションスタイリングに有効にできます。このように、一部のコントロールは以前のスタイルを保持してアプリケーションスタイリングの影響を受けないようにすることができ、その他のコントロールは組み込みのアプリケーションスタイリングのスタイルセットまたは Infragistics AppStylist™ for ASP.NET で作成した新しいスタイルセットを使用してスタイルまたはスタイル変更をすることができます。