////

|metadata|
{
    "name": "web-webnumericeditor",
    "controlName": ["WebNumericEditor"],
    "tags": [],
    "guid": "{3BD0A9B2-D7B0-4B53-B4B2-29D1C8152485}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T10:01:30Z"
}
|metadata|
////

= WebNumericEditor

このページには、WebNumericEditor™ コントロール関連の概要/タスクベースの情報がすべて含まれています。このセクションには、コントロールが何を実行するのか、またアプリケーションでなぜコントロールを使用したくなるのかから、コントロールを使用して一般的なタスクを完了する方法に関するステップバイステップの手順まで、コントロールに関する貴重な情報が含まれています。

WebNumericEditor コントロールについての詳細は、以下のリンクをクリックしてください。

== link:webnumericeditor-about-webnumericeditor.html[WebNumericEditor について]

このセクションには、WebNumericEditor コントロールの機能の理解を深めるのに役立つ情報があります。さらに、コントロールの目的も理解できます。

== link:webnumericeditor-using-webnumericeditor.html[WebNumericEditor の使用]

このセクションは、WebNumericEditor で使用可能な機能を使用する方法を示すタスクベースの情報を提供します。

== link:webnumericeditor-accessibility-compliance.html[WebNumericEditor アクセシビリティの遵守]

このトピックは、WebNumericEditor が第 508 条の要件を満たす方法を概略します。このアクセシビリティの遵守によって、エンドユーザー、特に障害を持つユーザーが WebNumericEditor コントロールを使用して構築された Web アプリケーションにアクセスおよび使用することを可能にします。

== link:webnumericeditor-api-overview.html[API の概要]

このトピックは、WebNumericEditor コントロールでプログラミング中に作業する名前空間とクラスをリストします。このトピックにリストされている名前空間とクラスは、{ProductName} ヘルプの「API 参照ガイド」セクションに便宜的にリンクされています。

== link:webtexteditor~infragistics.web.ui_namespace.html[CSOM の概要]

WebNumericEditor™ コントロールは、クライアント側の JavaScript プログラミング環境に堅牢なオブジェクト モデルを提供します。オブジェクト モデルは、十分な機能を備えた JavaScript オブジェクトで構成され、開発者はサーバー側にポストバックしなくても、コントロールに関連する重要な機能単位をプログラムできます。