////

|metadata|
{
    "name": "web-images",
    "controlName": [],
    "tags": ["FAQ","Styling"],
    "guid": "{D02671E6-BEAB-44F0-A09B-9491798B0BA3}",  
    "buildFlags": [],
    "createdOn": "2006-01-12T08:38:59Z"
}
|metadata|
////

= 画像

カスケード スタイル シートによるスタイリング オプションの一部の制限のために、画像はアプリケーション スタイリングにとって重要です。画像を使用すると、アプリケーションのための高度なスタイルを作成することができます。

画像を処理するときに留意すべきことは、ブラウザに画像ファイルへの明示的なパスを提供しなければならないということです。{ProductName} コンポーネントは、画像へのパスを定義するために、以下の 3 つの方法を使用します。

* 絶対 -- この画像パスは完全に指定され、サーバー ルートから開始します。
* 相対 -- 画像パスは、アプリケーション ルートに相対して指定されます。
* 解決 -- この画像パスは、 pick:[asp-net="link:{ApiPlatform}webui.shared{ApiVersion}~infragistics.webui.shared.iprovideappstyling~imagedirectory.html[ImageDirectory]"]  プロパティの組み合わせとして指定され、パスと画像ファイル名を提供します。Infragistics コンポーネントで作業するときに、このタイプの画像パスが最も頻繁に使用されます。アプリケーション スタイリングの画像ディレクトリは、画像で終了する StyleSetPath および StyleSetName 名の組み合わせです。たとえば、アプリケーション スタイリング ライブラリが ~/ig_res/Default にある場合、画像ディレクトリは ~/ig_res/Default/images に配置されます。

== 画像のグラデーション

コントロールおよびコンポーネントをスタイルするときに、グラデーションはますます人気が出ています。ところが ASP.NET では Windows フォームで実行できるようなグラデーションを作成できません。これはカスケードスタイルシートがこれを実行するための機能を提供しないからです。したがって、グラデーションが作成され、画像として保存されて、Windows フォームでグラデーション効果を真似るためにこれらの画像がコントロールに適用されます。

Infragistics AppStylist™ for ASP.NET には、グラデーション画像を作成できる機能が組み込まれてます。詳細は、 link:webappstylist-creating-a-gradient-background.html[「グラデーション背景を作成」]を参照してください。