////

|metadata|
{
    "name": "web-webdropdown",
    "controlName": ["WebDropDown"],
    "tags": ["Getting Started"],
    "guid": "{65E75279-3178-43D0-AF19-31212E991692}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebDropDown

このページには、WebDropDown™ コントロール関連の概要/タスクベースの情報がすべて含まれています。このセクションには、コントロールが何を実行するのか、またアプリケーションでなぜコントロールを使用したくなるのかから、コントロールを使用して一般的なタスクを完了する方法に関するステップバイステップの手順まで、コントロールに関する貴重な情報が含まれています。

WebDropDown コントロールについての詳細は、以下のリンクをクリックしてください。

== link:webdropdown-about-webdropdown.html[WebDropDown について]

このセクションには、WebDropDown コントロールの機能の理解を深めるのに役立つ情報があります。さらに、コントロールの目的も理解できます。

== link:webdropdown-getting-started-with-webdropdown.html[WebDropDown で開始]

このセクションは、WebDropDown コントロールで可能な限り迅速に起動および実行する方法についての情報を提供します。

== link:webdropdown-using-webdropdown.html[WebDropDown の使用]

このセクションは、WebDropDown で使用可能な機能を使用する方法を示すタスクベースの情報を提供します。

== link:webdropdown-accessibility-compliance.html[WebDropDown アクセシビリティの遵守]

このトピックは、WebDropDown が第 508 条の要件を満たす方法を概略します。このアクセシビリティの遵守によって、エンドユーザー、特に障害を持つユーザーが WebDropDown コントロールを使用して構築された Web アプリケーションにアクセスおよび使用することを可能にします。

== link:webdropdown-api-overview.html[API の概要]

このトピックは、WebDropDown コントロールでプログラミング中に作業する名前空間とクラスをリストします。このトピックにリストされている名前空間とクラスは、{ProductName} ヘルプの「API 参照ガイド」セクションに便宜的にリンクされています。

== link:webdropdown~infragistics.web.ui_namespace.html[クライアント サイド オブジェクト モデル (CSOM) の概要]

WebDropDown™ コントロールは、クライアント側の JavaScript プログラミング環境に堅牢なオブジェクト モデルを提供します。オブジェクト モデルは、十分な機能を備えた JavaScript オブジェクトで構成され、開発者はサーバー側にポストバックしなくても、コントロールに関連する重要な機能単位をプログラムできます。