////

|metadata|
{
    "name": "web-webtexteditor",
    "controlName": ["WebTextEditor"],
    "tags": [],
    "guid": "{1FE8CD62-269A-4B47-B848-97018D23A082}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebTextEditor

このページには、WebTextEditor™ コントロール関連の概要/タスクベースの情報がすべて含まれています。このセクションには、コントロールが何を実行するのか、またアプリケーションでなぜコントロールを使用したくなるのかから、コントロールを使用して一般的なタスクを完了する方法に関するステップバイステップの手順まで、コントロールに関する貴重な情報が含まれています。

WebTextEditor コントロールについての詳細は、以下のリンクをクリックしてください。

== link:webtexteditor-about-webtexteditor.html[WebTextEditor について]

このセクションには、WebTextEditor コントロールの機能の理解を深めるのに役立つ情報があります。さらに、コントロールの目的も理解できます。

== link:webtexteditor-using-webtexteditor.html[WebTextEditor の使用]

このセクションは、WebTextEditor で使用可能な機能を使用する方法を示すタスクベースの情報を提供します。

== link:webtexteditor-accessibility-compliance.html[WebTextEditor アクセシビリティの遵守]

このトピックは、WebTextEditor が第 508 条の要件を満たす方法を概略します。このアクセシビリティの遵守によって、エンドユーザー、特に障害を持つユーザーが WebTextEditor コントロールを使用して構築された Web アプリケーションにアクセスおよび使用することを可能にします。

== link:webtexteditor-api-overview.html[API の概要]

このトピックでは、WebTextEditor コントロールを使用してプログラミングするときに取り扱う名前空間とクラスのリストを掲載しています。このトピックにリストされている名前空間とクラスは、{ProductName} ヘルプの「API 参照ガイド」セクションに便宜的にリンクされています。

== link:webtexteditor~infragistics.web.ui_namespace.html[CSOM の概要]

WebTextEditor™ コントロールは、クライアント側の JavaScript プログラミング環境に堅牢なオブジェクト モデルを提供します。オブジェクト モデルは、十分な機能を備えた JavaScript オブジェクトで構成され、開発者はサーバー側にポストバックしなくても、コントロールに関連する重要な機能単位をプログラムできます。