////

|metadata|
{
    "name": "web-webrating",
    "controlName": ["WebRating"],
    "tags": ["Getting Started"],
    "guid": "871073ab-c989-4636-b275-65d62ad07e0e",  
    "buildFlags": [],
    "createdOn": "2010-06-01T04:42:24.7126693Z"
}
|metadata|
////

= WebRating

このページには、WebRating™ コントロール関連の概要/タスクベースの情報がすべて含まれています。このセクションには、コントロールが何を実行するのか、またアプリケーションでなぜコントロールを使用したくなるのかから、コントロールを使用して一般的なタスクを完了する方法に関するステップバイステップの手順まで、コントロールに関する貴重な情報が含まれています。

WebRating コントロールについての詳細は、以下のリンクをクリックしてください。

== link:webrating-about-webrating.html[WebRating について]

このセクションには、WebRating コントロールの機能の理解を深めるのに役立つ情報があります。さらに、コントロールの目的も理解できます。

== link:webrating-getting-started-with-webrating.html[WebRating で開始]

このセクションは、WebRating コントロールで可能な限り迅速に起動および実行する方法についての情報を提供します。

== link:webrating-using-webrating.html[WebRating の使用]

このセクションは、WebRating で使用可能な機能を使用する方法を示すタスクベースの情報を提供します。

== link:webrating-accessibility-compliance.html[WebRating アクセシビリティの遵守]

このトピックは、WebRating が第 508 条の要件を満たす方法を概略します。このアクセシビリティの遵守によって、エンドユーザー、特に障害を持つユーザーが WebRating コントロールを使用して構築された Web アプリケーションにアクセスおよび使用することを可能にします。

== link:webrating-api-overview.html[API の概要]

このトピックは、WebRating コントロールでプログラミング中に作業する名前空間とクラスをリストします。このトピックにリストされている名前空間とクラスは、{ProductName} ヘルプの「API リファレンス ガイド」セクションに便宜的にリンクされています。

== link:webrating~infragistics.web.ui_namespace.html[クライアント側オブジェクト モデル（CSOM）の概要]

WebRating™ コントロールは、クライアント側の JavaScript プログラミング環境に堅牢なオブジェクト モデルを提供します。オブジェクト モデルは、十分な機能を備えた JavaScript オブジェクトで構成され、開発者はサーバー側にポストバックしなくても、コントロールに関連する重要な機能単位をプログラムできます。