////

|metadata|
{
    "name": "web-styling-your-application",
    "controlName": [],
    "tags": ["Formatting","How Do I","Styling","Theming"],
    "guid": "{1490DBE1-1610-460C-BA50-59A39B27E075}",  
    "buildFlags": [],
    "createdOn": "2006-07-12T08:11:46Z"
}
|metadata|
////

= アプリケーションのスタイリング

アプリケーション スタイリングはグラフィック デザイナに Infragistics 独自の Infragistics AppStylist® for ASP.NET で作業する特権を与えます。Infragistics AppStylist は、より多くのコーディングを解放することでアプリケーション開発者を、また個々の技術を活用することでグラフィック デザイナを支援する画期的なアプリケーションです。ヘルプのこの特定のセクションは、スタイル ライブラリを作成および維持する、Infragistics AppStylist ユーザーインタフェースを理解する、またアプリケーションによりスタイリッシュなテーマを作成するために UI の異なるコントロールを使用することを支援することによって、Infragistics AppStylist for ASP.NET エクスペリエンスのすべての側面でグラフィックデザイナをガイドします。Infragistics AppStylist の詳細は以下のリンクをクリックしてください。

* link:webappstylist-introducing-application-styling-for-asp-net.html[ASP.NET のためのアプリケーション スタイリングの紹介]
* link:webappstylist-getting-started.html[はじめに]
* link:webappstylist-getting-to-know-netadvantage-appstylist-for-asp-net.html[Infragistics AppStylist for ASP.NET について]
* link:webappstylist-walkthroughs.html[詳細なガイド]