////

|metadata|
{
    "name": "web-webmonthcalendar",
    "controlName": ["WebMonthCalendar"],
    "tags": [],
    "guid": "{127F60EF-2DC8-4D15-AD4E-A36A4FD63F62}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebMonthCalendar

このページには、WebMonthCalendar™ コントロール関連の概要/タスクベースの情報がすべて含まれています。このセクションには、コントロールが何を実行するのか、またアプリケーションでなぜコントロールを使用したくなるのかから、コントロールを使用して一般的なタスクを完了する方法に関するステップバイステップの手順まで、コントロールに関する貴重な情報が含まれています。

WebMonthCalendar コントロールについての詳細は、以下のリンクをクリックしてください。

== link:webmonthcalendar-about-webmonthcalendar.html[WebMonthCalendar について]

このセクションには、WebMonthCalendar コントロールの機能の理解を深めるのに役立つ情報があります。さらに、コントロールの目的も理解できます。

== link:webmonthcalendar-getting-started-with-webmonthcalendar.html[WebMonthCalendar で開始]

このセクションは、WebMonthCalendar コントロールで可能な限り迅速に起動および実行する方法についての情報を提供します。

== link:webmonthcalendar-using-webmonthcalendar.html[WebMonthCalendar の使用]

このセクションは、WebMonthCalendar で使用可能な機能を使用する方法を示すタスクベースの情報を提供します。

== link:webmonthcalendar-accessibility-compliance.html[WebMonthCalendar アクセシビリティの遵守]

このトピックは、WebMonthCalendar が第 508 条の要件を満たす方法を概略します。このアクセシビリティの遵守によって、エンドユーザー、特に障害を持つユーザーが WebMonthCalendar コントロールを使用して構築された Web アプリケーションにアクセスおよび使用することを可能にします。

== link:webmonthcalendar-api-overview.html[API の概要]

このトピックは、WebMonthCalendar コントロールでプログラミング中に作業する名前空間とクラスをリストします。このトピックにリストされている名前空間とクラスは、{ProductName} ヘルプの「API 参照ガイド」セクションに便宜的にリンクされています。

== link:webmonthcalendar~infragistics.web.ui_namespace.html[クライアント側オブジェクト モデル（CSOM）の概要]

WebMonthCalendar™ コントロールは、クライアント側 JavaScript プログラミング環境に堅牢なオブジェクト モデルを提供します。オブジェクト モデルは、十分な機能を備えた JavaScript オブジェクトで構成され、開発者はサーバー側にポストバックしなくても、コントロールに関連する重要な機能単位をプログラムできます。