////

|metadata|
{
    "name": "web-whats-new-in-2011-volume-1",
    "controlName": [],
    "tags": ["FAQ","Getting Started"],
    "guid": "9f4f86f0-238c-4fb2-8cff-b01e340dc572",  
    "buildFlags": [],
    "createdOn": "2011-06-02T11:57:06.0944528Z"
}
|metadata|
////

= 2011 Volume 1 の新機能

{ProductName} 2011 Volume 1 リリースは以下の新機能を採用しています。

== 新しい Microsoft Word ライブラリ

Microsoft® Word® ライブラリによって、基本的な Word ドキュメントをプログラムで作成できます。これはクロス プラットフォームで、任意のインフラジスティックス製品に簡単に統合されます。

=== サポートされる Word の機能

このライブラリによってサポートされる最も重要な Word 機能は以下のとおりです。

*フォーマット機能*

** フォント スタイル
** ハイパーリンク
** 画像
** 表
** リスト
** 図形

*ドキュメント レイアウト機能*

** ページ サイズ
** 余白
** 改ページ
** ヘッダー/フッター

== 新しい IG テーマ

IG テーマは、最新のルック アンド フィールでアプリケーションを強化する完全なビジュアル テーマをアプリケーション開発者に提供するために作成されました。

== 新しい WebDataGrid/WebHierarchicalDataグリッド列タイプ

{ProductName} 2011 Volume 1 では、WebDataGrid™ コントロールおよび WebHierarchicalDataGrid™ コントロールの新機能のいくつかは、これらのコントロールの新しい列タイプに関係しています。

*チェック ボックス列タイプ*

ブール値（True/False）値のチェック ボックスを描画する機能だけでなく、提供されるコンバーターによってその他のタイプのデータを描画する機能をサポートします。
* *非バインド列タイプ*

グリッドの非バインド列をサポートします。これによって、ランタイムに計算して、追加のデータを列に入れることができます。

== 関連トピック

link:webdatagrid-columns.html[列]

== 新しい WebDataGrid/WebHierarchicalDataグリッドのカスタムのデータ バインド

カスタムのデータ バインド機能によって、WebDataGrid/WebHierarchicalDataGrid は純粋なユーザー インターフェイス（UI）コントロールのように動作することができます。並べ替え、フィルター処理、ページングのような一般的な機能をコードで処理することが可能となりました。これでグリッドは UI の状態を保持する間にどのようなカスタム データが提供されてもランタイムに描画するだけです。

== 新しい WebHierarchicalDataGrid 行編集テンプレート

WebHierarchicalDataGrid は行編集テンプレートによりカスタムの編集シナリオをサポートするようになりました。この機能によって、メインのインターフェイスに表示される列をプログラムによって制限することが可能になりますが、ユーザーは必要な場合に追加情報をドリルダウンできます。

== 新しい WebHierarchicalDataGrid 列の移動とサイズ変更

WebHierarchicalDataGrid は移動可能な列だけでなく、列のサイズ変更をサポートするようになりました。この機能は、WebDataGrid ですでに使用可能な機能と似ています。列の移動とサイズ変更は親バンドと子バンドの両方で有効にできます。

== 関連トピック

link:webhierarchicaldatagrid-column-moving.html[列の移動]

link:webhierarchicaldatagrid-column-resizing.html[列のサイズ変更]

== 新しい WebDropDown クライアントのバインド

WebDropDown™ は、サーバーから一切 HTML マークアップを期待することなく、クライアントでの JSON データの描画をサポートするようになりました。すべての WebDropDown 機能は、候補、仮想スクロール、フィルター処理など新しい機能でサポートされます。

== Persistence Framework

新しい Persistence Framework によってコントロールでのエンドユーザーの設定のシリアル化が容易になります。WebDataGrid/WebHierarchicalDataGrid コントロールは、このリリースにも含まれる特別な実装を使用します。開発者は、フレームワークを拡張して、任意の ASP.NET コントロールへのより優れた統合を可能にします。

== 関連トピック

link:persistenceframework-about-persistence-framework.html[Persistence Framework について]

link:persistenceframework-getting-started-with-persistence-framework.html[Persistence Framework で開始]

== 新しい WebVideoPlayer HTML5 限定のコントロール

Web 開発においてオープン スタンダードがより大きい役割を今後も果たし続けることから、インフラジスティックスはもうひとつの HTML 5 コントロール、WebVideoPlayer™ をリリースしました。WebVideoPlayer は、ブックマーク、バナーおよび埋め込み広告、関連ビデオの表示、カスタムスタイリングなどをサポートします。

== 関連トピック

link:webvideoplayer-overview.html[WebVideoPlayer の概要]

== 新しい WebUpload コントロール

WebUpload™ コントロールは、ユーザーが単一ファイルまたは複数ファイルを同時にアップロードすることを可能にする多くの人が求めているコントロールです。このコントロールは、各アップロードをキャンセルするためのインターフェイスもユーザーに提供します。

== 関連トピック

link:webupload-overview.html[WebUpload 概要]