////

|metadata|
{
    "name": "web-preparing-your-application-for-application-styling",
    "controlName": [],
    "tags": ["Styling"],
    "guid": "{E32106CC-79FB-4D73-A23F-67B3528184B0}",  
    "buildFlags": [],
    "createdOn": "2007-10-04T14:43:23Z"
}
|metadata|
////

= アプリケーション スタイリング用にアプリケーションを準備する

このトピックには、アプリケーション スタイリングを有効にした時に遭遇する問題、そしてアプリケーションの現在の状態に基づいてこれらの問題を解決する方法についての有益な情報が含まれます。

== 既存のアプリケーションでアプリケーション スタイリングを有効にする前に

* ひとつのコントロールまたはページでアプリケーション スタイリングを有効にすることで開始します。これによってアプリケーション全体に影響を及ぼすことなくコントロールまたはページ行われた変更を確認できます。詳細については、 link:web-changing-stylesets-at-the-control-level.html[コントロール レベルで StyleSets を変更]および link:web-enabling-application-styling-using-the-webpagestyler-component.html[WebPageStyler コンポーネントを使用してアプリケーション スタイリングを有効にする]を参照してください。

== デフォルト設定が削除された

WebGrid™、WebCombo™ および WebListbar™ は、2007 Volume 1 リリースをアップグレードしアプリケーション スタイリングを有効にすると若干異なって表示されます。 link:web-application-styling-framework-asf.html[Application Styling Framework (ASF)] を完了するには、デフォルト設定を削除することで後方互換性を失う困難な決定を行わなければなりませんでした。上記のコントロールでは、値が入力されていない場合、BorderStyle、BorderWidth、BorderColor などの設定が想定されます。ただし、外部のスタイルシートから境界スタイルを指定することを決定した場合は問題が生じます。

プロジェクトをアップグレード後に Microsoft® Visual Studio® でフォームを開くことでこれを回避できます。デザイン ビューでは、コントロールのショートカット メニューで [デフォルト スタイルを設定] を選択します。その代わりに、ランタイムでコントロールの SetDefaultStyleSettings メソッドを呼び出すことができます。

== アプリケーション スタイリング用にアプリケーションを準備する場合の共通のシナリオ

このセクションは、Web アプリケーションの現在の段階に関係する共通のシナリオを説明します。各シナリオには、アプリケーション スタイリング用の新しい Web アプリケーションまたは既存の Web アプリケーションを準備するためにユーザーを支援する重要情報があります。

== 新しいアプリケーションを作成

コントロールを Web フォームに配置する前にアプリケーション スタイリングを有効にすることが大切です。コントロールが Web フォームにドロップされると、すべてのデフォルト スタイルおよびプリセットはコントロールに適用されません。その代わりに、コントロールのスタイルは、アプリケーションスタイリングが有効である場合に選択された StyleSet（たとえば、Appletini）によって決定されます。詳細は、 link:web-upgrading-web-applications-to-make-use-of-application-styling.html[Web アプリケーションをアップグレードしてアプリケーション スタイリングを使用可能にする]を参照してください。

== アプリケーション スタイリングを有効にせずに既存のアプリケーションで作業

ご使用のアプリケーションでアプリケーション スタイリングが有効でない場合、デフォルトの動作が保持されます。言い換えると、デフォルト スタイルおよびプリセットの両方または一方は、{ProductName} の前バージョンと同様に適用されます。

== 既存のアプリケーション用にアプリケーション スタイリングを有効にする

既存のアプリケーションでアプリケーション スタイリングを有効にする場合、デザインまたはソース ビューでコントロールに現在適用されているスタイルを手動で削除する必要があります。コントロールのさまざまなスタイル ポイント用のデフォルト CSS 値を確立することで ASF は機能するので、コントロールに設定されたスタイル ポイントが（たとえば、過去に適用されたプリセット）優先され、アプリケーション スタイリング値を無効にします。アプリケーション スタイリングが正しく適用されるためには、現在適用されているスタイルを手動で削除する必要があります。詳細は、 link:web-upgrading-web-applications-to-make-use-of-application-styling.html[Web アプリケーションをアップグレードしてアプリケーションスタイリングを使用可能にする]を参照してください。

*注：* デザイン タイムでコントロールのショートカットで使用できる [デフォルト スタイルをリセット] を使用する場合、WebGrid で内部的に設定されたデフォルト スタイル設定だけがクリアされます。WebGrid で設定されていない他のデフォルト スタイルはそのまま機能します。