////

|metadata|
{
    "name": "web-webcalcmanager",
    "controlName": ["WebCalcManager"],
    "tags": ["Getting Started"],
    "guid": "{43DAC7D2-8D2A-4E27-9859-CF0C9673A77F}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebCalcManager

WebCalcManager™ コンポーネントに関連した概要/タスクベースの情報をすべて網羅している記述を探していた方は、ちょうどぴったりのセクションに到達しました。このセクションは、コンポーネントについての概要からアプリケーションで使用する理由、コンポーネントを使用して一般的なタスクを完了するための方法の手順などのWebCalcManagerについての有益な情報を含んでいます。

== link:webcalcmanager-understanding-webcalcmanager.html[WebCalcManagerの理解]

このセクションでは、WebCalcManager コンポーネントの機能をより良く理解するために助けとなるあらゆる情報や、アプリケーション構築の一環としてこのコンポーネントの機能を使いたくなる理由が説明されています。

== link:web-webcalcmanager-using-webcalcmanager.html[WebCalcManager の使用]

このセクションは、WebCalcManager™ コントロールによって提供されるさまざまな特徴や機能を効率的に使用するための手助けとなるタスクベースの情報のゲートウェイです。

== link:webcalcmanager-api-overview.html[API の概要]

このトピックは、 WebCalcManagerコンポーネントでプログラミング中に作業する名前空間とクラスをリストします。このトピックにリストされている名前空間とクラスは、{ProductName} ヘルプの「API 参照ガイド」セクションに便宜的にリンクされています。