////

|metadata|
{
    "name": "webcurrencyeditor-setting-minimum-and-maximum-values-for-webcurrencyeditor",
    "controlName": ["WebCurrencyEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{BA5204A7-FF0D-4E01-A384-0DE3167843CE}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T16:39:53Z"
}
|metadata|
////

= WebCurrencyEditor の最大値と最小値を設定

WebCurrencyEditor™ によってコントロールの  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~minvalue.html[MinValue]"]  プロパティと  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~maxvalue.html[MaxValue]"]  プロパティを設定するだけでエンドユーザーがエディターに入力できる通貨値の範囲を設定できます。エンドユーザーが最大値よりも大きい通貨値を入力すると、エディターはその値を最大値に設定します。同様に、エンドユーザーが最小値よりも小さい通貨値を入力すると、エディターはその値を最小値に設定します。

Microsoft® Visual Studio® [プロパティ] ウィンドウを使用する、または以下のコードを使用することによって、MinValue プロパティと MaxValue プロパティを設定できます:

*Visual Basic の場合：*

----
WebCurrencyEditor1.MinValue = 25
WebCurrencyEditor1.MaxValue = 100
----

*C# の場合：*

----
WebCurrencyEditor1.MinValue = 25;
WebCurrencyEditor1.MaxValue = 100;
----

*JavaScript の場合：*

----
var Editor = $find("WebCurrencyEditor1");
Editor.set_minValue(25);
Editor.set_maxValue(100);
----