////

|metadata|
{
    "name": "webcurrencyeditor-using-display-factor-in-webcurrencyeditor",
    "controlName": ["WebCurrencyEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{E83C7FE3-BB58-4940-87FF-D22F141B03BC}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebCurrencyEditor で表示係数を使用

WebCurrencyEditor™ によってコントロールで値を乗じる係数を設定することが可能となり、エディターにテキストとして表示します。たとえば、表示係数が 100 でエンドユーザーがエディターに 80 と入力すると（コントロールの  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~text.html[Text]"]  プロパティによって影響される）、エディターの  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~value.html[Value]"]  プロパティは 0.8 になります。コントロールの  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~displayfactor.html[DisplayFactor]"]  プロパティを設定するだけで表示係数を設定することができます。デフォルトでこのプロパティは 1 に設定されます。

*Visual Basic の場合：*

----
WebCurrencyEditor1.DisplayFactor = 10
----

*C# の場合：*

----
WebCurrencyEditor1.DisplayFactor = 10;
----