////

|metadata|
{
    "name": "webdatagrid-events",
    "controlName": ["WebDataGrid"],
    "tags": ["Events","Grids"],
    "guid": "{90D6D027-0F03-4D19-B796-86DE7B083CE9}",  
    "buildFlags": [],
    "createdOn": "2008-09-09T14:05:01Z"
}
|metadata|
////

= イベント

== サーバーおよびクライアント イベント

WebDataGrid™ コントロールの多くの動作にはサーバー側イベントとクライアント側イベントの両方があります。これらのイベントは発生する順序を反映して接尾辞 "ing" または "ed" が追加されます。動作に基づいて、"ing" イベントと "ed" イベントの 2 つのイベントが各側に通常あります。

たとえば、 pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.behaviors~editingcore.html[EditingCore]"]  動作にはサーバーとクライアントの両方に RowUpdating および RowUpdated イベントがあります。

== イベントの順序

これらのイベントが起動する順序は、WebDataGrid で何が発生するのかによって異なります。ただし基本的な順序は以下のとおりです。"ing" イベントは "ed" の前に発生します。通常クライアントからサーバーへ、そしてクライアントに戻るという順序です。

たとえば、AJAX を有効にして WebDataGrid を更新すると、更新を起動するために行から移動するとイベントは以下の順序になります:

[start=1]
. クライアント側の RowUpdating
[start=2]
. サーバー側の RowUpdating
[start=3]
. サーバー側の RowUpdated
[start=4]
. クライアント側の RowUpdated

このイベントの順序によって、イベントがクライアント側で発生する前に任意のタイプのカスタムの操作を実行できます。必要な場合には別の機会がサーバーで与えられます。次にイベントがサーバーまたはクライアントで発生した後で任意のタイプの操作を実行できます。

== 関連トピック

link:webdatagrid-cancel-an-event-in-webdatagrid.html[WebDataGrid でイベントをキャンセル]

link:webdatagrid-handle-an-event-in-webdatagrid.html[WebDataGrid でイベントを処理]

link:webdatagrid-using-itemcommand-event.html[WebDataGrid で ItemCommand イベントを使用]