////

|metadata|
{
    "name": "webdatagrid-supported-data-sources",
    "controlName": ["WebDataGrid"],
    "tags": ["Data Binding","Grids"],
    "guid": "{B50810DC-F840-4CDC-9030-F72E0A737FBD}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= サポートされるデータ ソース

== データ バインディング

WebDataGrid™ はデータ バインディングのために解明できるアプローチを使用します。これはデータ ソースによって返されるすべてのレコードが WebDataGrid によって表示されるということを意味します。コントロールに表示したくないフィールドを指定する必要があります。

WebDataGrid は完全なフラット データ コントロールです: 1 レベルのデータのみ表示します。使用するデータ ソースが階層データのみを含む場合、デフォルトで表示するのはルート レベルのデータのみです。 pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.iband~datamember.html[DataMember]"]  プロパティを使用してどのレベルのデータを表示するのかを指定できます。

データへのバインドは、ランタイムに DataSource プロパティを設定する、またはデザインタイムまたはランタイムに  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.framework.data.flatdataboundcontrol~datasourceid.html[DataSourceID]"]  プロパティを設定する必要があります。Page PreRender イベントでまたは行をアクセスするための最初の試みでデータが自動的に要求されるために、DataBind への明示的な呼び出しは不要です。

== データ操作

元となるデータ ソースによってサポートされる操作は、そのデータ ソースのメカニズムを使用して実行されます。操作がデータ ソースによってサポートされずに WebDataGrid によってサポートされる場合には、その操作は WebDataGrid によって内部で実行されます。たとえば、すべてのデータ ソースがソートされたデータを返せるわけではなく、この機能を実装しないデータ ソースの場合、WebDataGrid はデータをソートするために固有の実装を使用します。

== データの更新

CRUD 操作には、内部メカニズムは採用されていません。WebDataGrid は基本データ ソースのメカニズム使用して自動的に変更を保持しようとします。これは、データ ソース コントロールが CRUD 操作をサポートしない場合、このような機能を提供するために手動でこれらの操作を処理する必要があります。

== サポートされるデータ ソース

WebDataGrid は Microsoft® データ ソース コントロール、データ テーブル、および IEnumerable を実装するデータ エンティティへのバインドをサポートします。

以下の表はサポートされるデータ ソースを表示し、特定のデータ操作に対するサポートの状態を表します。サポートの状態は以下のとおりです。

* はい - 自動的にサポート。
* 構成 - データ ソースはサポートのために構成する必要があります。
* 実装 - データ ソースはサポートのために適切なインターフェイスを実装する必要があります。

[options="header", cols="a,a,a,a,a,a,a"]
|====
|データ ソース|並べ替え|ページ|フィルター|自動更新|自動削除|自動挿入

|配列
|はい
|はい
|はい
|いいえ
|いいえ
|いいえ

|AccessDataSource
|はい
|はい
|はい
|構成
|構成
|構成

|DataSet
|はい
|はい
|はい
|いいえ
|いいえ
|いいえ

|DataTable
|はい
|はい
|はい
|はい
|はい
|はい

|DataView
|はい
|はい
|はい
|いいえ
|いいえ
|いいえ

|DomainDataSource
|はい
|はい
|はい
|構成
|構成
|構成

|IBindingList
|はい
|はい
|はい
|いいえ
|いいえ
|いいえ

|ICollection
|はい
|はい
|はい
|いいえ
|いいえ
|いいえ

|IEnumerable
|はい
|はい
|はい
|いいえ
|いいえ
|いいえ

|IHierarchicalEnumerable
|はい
|はい
|はい
|いいえ
|いいえ
|いいえ

|IList
|はい
|はい
|はい
|いいえ
|いいえ
|いいえ

|IQueryable
|はい
|はい
|はい
|実装
|実装
|実装

|LinqDataSource
|はい
|はい
|はい
|構成
|構成
|構成

|ObjectDataSource
|はい
|はい
|はい
|構成
|構成
|構成

|SqlDataSource
|はい
|はい
|はい
|構成
|構成
|構成

|====