////

|metadata|
{
    "name": "webdatagrid-accessibility-compliance",
    "controlName": ["WebDataGrid"],
    "tags": ["Section 508"],
    "guid": "{4185BBA7-A29C-466B-A87C-11E88053B5AA}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebDataGrid アクセシビリティの遵守

弊社の ASP.NET コントロールおよびコンポーネントはすべて、1973 年のリハビリテーション法第 508 条第 1194 部 22 条をさまざまな程度で順守しています。コントロールの法令遵守の概要については、 link:web-accessibility-overview.html[この表を参照してください]。以下の表は、WebDataGrid コントロールの 1194 部 22 条のルールおよびコントロールの法令遵守を含みます。プロパティを設定する場合があります。その他の場合は設定する必要はありません。機能は定義済みです。

セクションがリストされていない場合、コントロールはそのセクションとの法令遵守がない、または適用できません。

[options="header", cols="a,a"]
|====
|規則|規則を遵守する方法

|(a)
|主要な機能を持つすべての IMG タグは "alt" 属性プロパティが設定されるか、alt 属性値の設定が可能です。

|(c)
|クライアント側イベントを使用すると、現在の状態（アクティブ化されている、選択されている、無効というように）を反映するいかなるコントロールの DOM 要素の属性をユーザーは変更できます。このように色（またはスタイル）によって伝達される情報はスクリーン リーダーで使用できます。CSS を使用しても (グレースケールを含む) 任意の色で WebDataGrid™ のスタイルを指定できます。

|(l)
|コントロールのスクリプトがページのマークアップを変更するようになっていても、規則 (a) と (c) に示す属性が定義されているため、変更後のコンテンツはスクリーン リーダーに適合したものになります。

|(n)
|コントロールの TabIndex プロパティを 0 よりも大きい値に設定することによって、コントロールはページのタブ シーケンスに参加し、フォーカスを受け取ります。 

* TAB -- 次の行/セルをアクティブにします。 

* SHIFT+TAB -- 前の行/セルをアクティブにします。 

* CTRL+TAB -- アクティブの行とアクティブなセルを切り替えます。 

* スペースバー -- アクティブなセルがチェックボックスの場合、そのチェックされた状態を切り替えます。そうでない場合にはアクティブの行を選択/選択を解除します。 

* 左矢印 -- セルがアクティブなとき、前のセルをアクティブにします。行がアクティブのとき、子の行アイランドがある場合には縮小します。 

* 右矢印 -- セルがアクティブなとき、次のセルをアクティブにします。行がアクティブのとき、子の行アイランドがある場合には展開します。 

* 上矢印 -- 前の行にある行/セルをアクティブにします。 

* 下矢印 -- 次の行にある行/セルをアクティブにします。 

* SHIFT+上（または下）矢印 -- 複数行選択に上（または下）行を含みます。 

* ENTER/PAGE DOWN -- セルがセル ボタンの場合、クリックと同じ働きをします。セルに Target URL がある場合、その URL に移動します。Target URL がない場合は次の行に移動します。 

* SHIFT & ENTER/PAGE UP -- ひとつ前の行に移動します。 

* DEL -- 現在の行を削除します。 

一括更新機能が有効になっている場合: 

* ENTER/SPACE - 行を削除した場合、削除した行の上にマウス ポインターをあてると [元に戻す] ボタンが現れます。このときに ENTER または SPACE キーを押すと、マウス クリックを行った場合と同じように [元に戻す] ボタンを押したことになります (この結果、その行が復元します)。 

* CTRL + Z - 行に対して行った変更 (編集) を元に戻します。 

|(o)
|(n) で述べたナビゲーション キーの一部を使用してこれを実現できます。

|====