////

|metadata|
{
    "name": "webdatagrid-api-overview",
    "controlName": ["WebDataGrid"],
    "tags": ["API","Grids"],
    "guid": "{F9CE1B44-89B7-49E5-9FD8-08267BAF3FCF}",  
    "buildFlags": [],
    "createdOn": "2008-07-10T11:16:43Z"
}
|metadata|
////

= API の概要

このセクションではコントロールに関連する各名前空間を示します。このコントロールでプログラムする間に使用するいくつかのキー クラスも提供します。このページの名前空間とクラスは当社の API マニュアルに直接リンクします。

=== WebDataGrid 名前空間:

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols_namespace.html[Infragistics.Web.UI.GridControls]"]

=== キー クラス:
link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.behaviors.html[Behaviors]

link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridfield.html[GridField]

link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridrecord.html[GridRecord]

link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.gridrecorditem.html[GridRecordItem]

link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.webdatagrid.html[WebDataGrid]