////

|metadata|
{
    "name": "webdatamenu-keyboard-navigation",
    "controlName": ["WebDataMenu"],
    "tags": [],
    "guid": "{7DBC7669-B0C3-4891-931D-3C37560FBEAE}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= キーボード ナビゲーション

WebDataMenu™ は非常に簡単にキーボードを使用したメニュー項目のナビゲートをサポートします。

* *上矢印* -- 項目が垂直に描画される場合（垂直方向のメニューのルート項目、または垂直方向のサブメニュー（これがデフォルト）のいずれか）、エンドユーザーは前の無効になっていない項目に移動し、最初の項目の場合、最後の項目に移動します。メニュー/サブメニューの項目が水平に描画され、現在の項目に子がある場合、何も発生しません。メニュー/サブメニューの項目が垂直に描画され現在の項目に子がない場合、親項目が選択されます。
* *下矢印* -- 項目が垂直に描画される場合（垂直方向のメニューのルート項目、または垂直方向のサブメニュー（これがデフォルト）のいずれか）、エンドユーザーは次の無効になっていない項目に移動し、最後の項目の場合、最初の項目に移動します。メニュー/サブメニューの項目が水平に描画され、現在の項目に子がある場合、サブメニューが開いて最初の項目が選択されます。メニュー/サブメニューの項目が垂直に描画され、現在の項目に子がない場合、何も発生しません。
* *右矢印* -- 項目が水平に描画される場合（水平方向のメニューのルート項目、または水平方向のサブメニューのいずれか）、エンドユーザーは次の無効になっていない項目に移動し、最後の項目の場合、最初の項目に移動します。メニュー/サブメニューの項目が垂直に描画され、現在の項目に子がある場合、サブメニューが開いてその最初の子が選択されます。メニュー/サブメニューの項目が垂直に描画され現在の項目に子がない場合、現在のサブメニューが閉じられて親が選択されます。
* *左矢印* -- 項目が水平に描画される場合（水平方向のメニューのルート項目、または水平方向のサブメニューのいずれか）、エンドユーザーは前の無効になっていない項目に移動し、最初の項目の場合、最後の項目に移動します。メニュー/サブメニューの項目が垂直に描画され、現在の項目に子がある場合、何も発生しません。メニュー/サブメニューの項目が垂直に描画され現在の項目に子がない場合、現在のサブメニューが閉じられて親が選択されます。
* *Enter* -- そのメニュー項目のクリック イベントと選択イベントを発生させます。
* *Tab* -- ページ上で次のプレーンの DOM 要素またはコントロールにフォーカスを移動します。
* *スペース* -- 項目上でスペース バーを押すとまだ選択されてない場合には項目が選択され、最後の選択された項目の選択が解除されます。項目がすでに選択されている場合には選択が解除されます。したがってメニューから選択全体が削除されます。