////

|metadata|
{
    "name": "webdatepicker-autofilling-the-year-field-in-webdatepicker",
    "controlName": ["WebDatePicker"],
    "tags": ["Tips and Tricks"],
    "guid": "{D422BD38-74C7-463D-A706-EE7998303147}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebDatePicker で年フィールドをオートフィル

WebDatePicker™ はエンドユーザーが 1 桁または 2 桁の数字を入力すると年フィールドを自動的に 4 桁に埋めます。ただし、年フィールドを 20 世紀または 21 世紀に自動的に埋めるためにコントロールの  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webdatetimeeditor~centurythreshold.html[CenturyThreshold]"]  プロパティを使用して -1 から 99 の値を設定できます。プロパティを -1 に設定すると、オートフィルは無効になります。入力された年がプロパティの値に等しいかそれより小さい場合、2000 が年フィールドに追加されます。入力された年がプロパティの値より大きく、かつ 100 より小さい場合、1900 が年フィールドに追加されます。たとえば、YearToFill プロパティを 45 の値に設定し、エンドユーザーが 45 より小さいまたは 45 に等しい年を入力すると、WebDatePicker は年に 2000 を追加します。エンドユーザーが 45 より大きく、かつ 100 より小さい場合、1900 が年フィールドに追加されます。デフォルトでは、CenturyThreshold プロパティは 29 に設定されます。

*Visual Basic の場合：*

----
WebDatePicker1.CenturyThreshold = 45
----

*C# の場合：*

----
WebDatePicker1.CenturyThreshold = 45;
----

*JavaScript の場合：*

----
$find("WebDatePicker1").set_centuryThreshold(45);
----