////

|metadata|
{
    "name": "webexcelexporter-saving-exported-data-on-the-server",
    "controlName": ["WebExcelExporter"],
    "tags": ["Exporting","Grids","Persistence"],
    "guid": "7e87e074-701d-4af4-9e8c-ebdbb2294517",  
    "buildFlags": [],
    "createdOn": "2010-06-06T07:51:03.4626939Z"
}
|metadata|
////

= エクスポートしたデータをサーバーに保存

== 達成すること

WebDataGrid/WebHierarchicalDataGrid データを Microsoft™ Excel™ ファイルにエクスポートして Web サーバーのハードディスクに保存するように WebExcelExporter を設定および使用する方法を学習します。

== 始める前に

ここに示すサンプルをコンパイルおよび実行するためには、NetAdvatage for ASP.NET v. 10.2 をインストールする必要があります。SQL サーバー（Express またはその他任意のエディション）の実行中のインスタンスも必要となりますが、SQL サーバーのインスタンスに NorthWind データベースを添付することも必要となります。 link:http://msdn.microsoft.com/ja-JP/library/8b6y4c7s.aspx[http://msdn.microsoft.com/ja-JP/library/8b6y4c7s.aspx] にある指示に従い NorthWind データベースをインストールするか、 link:http://www.microsoft.com/downloads/details.aspx?familyid=06616212-0356-46a0-8da2-eebc53a68034&displaylang=en[http://www.microsoft.com/downloads/details.aspx?familyid=06616212-0356-46a0-8da2-eebc53a68034&displaylang=en] (英語) から直接データベースをダウンロードすることができます。

== エクスポートしたデータをサーバー上のファイルに保存

以下の手順に従ってデータを Microsoft Office Excel™ 2003 ファイル形式にエクスポートしサーバーのハードディスク上にファイルを保存します。

[start=1]
. WebDataGrid を SqlDataSource コントロールにバインドして Web ページ（ASP.NET Web フォーム）を作成します。SqlDataSource コントロールは、Northwind Customers テーブルからデータを取得するように構成されます。

*HTML の場合:*

----
<ig:WebDataGrid runat="server" ID="wdgEmpoyees" 
            DataSourceID="SqlDsEmployees" 
            DataKeyFields="EmployeeID" 
            AutoGenerateColumns="true"
            >
            </ig:WebDataGrid>
<asp:SqlDataSource ID="SqlDsEmployees" runat="server" 
    ConnectionString="<%$ ConnectionStrings:NorthwindConnectionString %>" 
    SelectCommand="SELECT [EmployeeID], [LastName], [FirstName], [Title], [ReportsTo] FROM [Employees]">
</asp:SqlDataSource>
----

[start=2]
. WebExcelExporter コントロールを Visual Studio Toolbox からページにドラッグします。

.. WebExcelExporter の ExportMode プロパティを Custom に設定します。
.. コントロールの ID プロパティを WebExcelExporter に設定します。
.. コントロールの DownloadName プロパティを ExportedData に設定します。

*HTML の場合:*

----
<ig:WebExcelExporter runat="server" ID="WebExcelExporter" ExportMode ="Custom" DownloadName="ExportedData" />
----

[start=3]
. Button コントロールを Visual Studio Toolbox からページにドラッグします。

.. ボタンの ID プロパティを btnExport に設定します。
.. コントロールの Text プロパティを「データのエクスポート」に設定します。
.. コントロールの OnClick プロパティを btnExport_Click に設定します。
.. コード ビハインドで btnExport_Click ハンドラーを定義し、WebExcelExporter の Export() メソッド オーバーロードのひとつを呼び出します。

[cols="a"]
|====
|コード ビハインド（C#）の場合:

|protected void btnExport_Click(object sender, EventArgs e) 

{ 

Infragistics.Documents.Excel.WorkbookFormat excelFormat = Infragistics.Documents.Excel.WorkbookFormat. Excel97To2003; 

Infragistics.Documents.Excel.Workbook wBook = new Infragistics.Documents.Excel.Workbook(excelFormat); 

this.WebExcelExporter.Export(this.wdgEmpoyees, wBook); 

string tmpName = Server.MapPath("~/exported_data/GridData.xls"); wBook.Save(tmpName); 

}

|====

*HTML の場合:*

----
<asp:Button runat="server" ID="btnExport" Text="データのエクスポート" OnClick="btnExport_Click" />
----

[start=4]
. アプリケーションを実行します。
[start=5]
. [データのエクスポート] ボタンをクリックします。
[start=6]
. アプリケーション関係フォルダー exported_data で GridData.xls という名前のファイルをチェックします。これにはエクスポートされたデータが含まれます。


*注：* GridData.xls ファイルは Grid の表示可能なデータしか含みません。