////

|metadata|
{
    "name": "webhierarchicaldatagrid-api-overview",
    "controlName": ["WebHierarchicalDataGrid"],
    "tags": ["API","Grids","How Do I"],
    "guid": "{C403B751-2540-450A-8668-F9F768D30664}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= API の概要

このセクションではコントロールに関連する各名前空間を示します。このコントロールでプログラムする間に使用するいくつかのキー クラスも提供します。このページの名前空間とクラスは当社の API マニュアルに直接リンクします。

=== WebHierarchicalDataGrid 名前空間：

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols_namespace.html[Infragistics.Web.UI.GridControls]"]

=== キー クラス：

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.band.html[Band]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.bandcollection.html[BandCollection]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.containergrid.html[ContainerGrid]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.containergridcollection.html[ContainerGridCollection]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.behaviors.html[Behaviors]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.webhierarchicaldatagrid.html[WebHierarchicalDataGrid]"]