////

|metadata|
{
    "name": "webhierarchicaldatagrid-accessibility-compliance",
    "controlName": ["WebHierarchicalDataGrid"],
    "tags": ["Grids","Section 508"],
    "guid": "{7658F67E-29B3-49CD-A9AE-BB75504AD671}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebHierarchicalDataGrid アクセシビリティの遵守

弊社の ASP.NET コントロールおよびコンポーネントはすべて、1973 年のリハビリテーション法第 508 条第 1194 部 22 条を遵守しています。以下は、コントロールに関係する第 1194 部 22 条の特定の規則と各規則を遵守する方法を含んだ表です。場合によって、プロパティを設定する必要があります。それ以外の場合には、コントロールがすべての作業を実行するため、ユーザーは何もする必要がありません。

[options="header", cols="a,a"]
|====
|規則|規則を遵守する方法

|(c)
|クライアント側イベントを使用すると、現在の状態（アクティブ化されている、選択されている、無効というように）を反映するいかなるコントロールの DOM 要素の属性をユーザーは変更できます。このように色（またはスタイル）によって伝達される情報はスクリーン リーダーで使用できます。

|(n)
|コントロールの TabIndex プロパティを 0 よりも大きい値に設定することによって、コントロールはページのタブ シーケンスに参加し、フォーカスを受け取ります。 

* TAB -- 次の行/セルをアクティブにします。 

* SHIFT+TAB -- 前の行/セルをアクティブにします。 

* CTRL+TAB -- アクティブの行とアクティブなセルを切り替えます。 

* スペースバー -- アクティブなセルがチェックボックスの場合、そのチェックされた状態を切り替えます。そうでない場合にはアクティブの行を選択/選択を解除します。 

* 左矢印 -- セルがアクティブなとき、次のセルをアクティブにします。行がアクティブのとき、子の行アイランドがある場合には展開します。 

* 右矢印 -- セルがアクティブなとき、前のセルをアクティブにします。行がアクティブのとき、子の行アイランドがある場合には縮小します。 

* 上矢印 -- 前の行にある行/セルをアクティブにします。現在の行アイランド内に限って適用されます。SHIFT+TAB を押して、行アイランドの最初の行から親行に移動します。 

* 下矢印 -- 次の行にある行/セルをアクティブにします。現在の行アイランド内に限って適用されます。TAB を押して、行アイランドの最後の行から親バンドの次の行に移動します。 

* CTRL+下矢印 -- XML レンダリングを使用するときに AJAX を通して行の次のバッチを検索します。 

* SHIFT+上（または下）矢印 -- 複数行選択に上（または下）行を含みます。現在の行アイランド内に限って適用されます。 

* ENTER -- セルがセル ボタンの場合、クリックを起動します。セルの Target URL が存在する場合はそれにナビゲートします。 

* DEL -- 現在の行を削除します。 

* HOME -- セルがアクティブのとき、その行内の最初の表示されるセルをアクティブにします。行がアクティブのとき、ページ上の最初の行をアクティブにします。 

* END -- 行の最後の表示されるセルをアクティブにします。行がアクティブのとき、ページ上の最後の行をアクティブにします。 

* +/- + キーを押すと、子がある場合、アクティブ行が展開されます。同様に、- キーを押すと、アクティブ行が縮小されます。 

|====