////

|metadata|
{
    "name": "webhierarchicaldatagrid-behaviors",
    "controlName": ["WebHierarchicalDataGrid"],
    "tags": ["Editing","Filtering","Grids","How Do I","Paging"],
    "guid": "{DFD13F66-0E57-470C-930C-E991384963D1}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= 動作

WebHierarchicalDataGrid™ は、WebDataGrid™ で使用できる動作の多くをサポートします。 pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.iband.html[IBand]"]  インターフェイスを実装するすべてのオブジェクトは動作設定を公開します。つまり、Band オブジェクトと  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.containergrid.html[ContainerGrid]"]  オブジェクトの動作を設定できることになります。多くの動作は子グリッド/バンドで継承可能ですが、それ以外の動作はコントロールのトップ レベルに限り設定できます。固有の継承可能な動作は、子グリッドが動作設定を継承するかどうかを制御するために  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.sorting~enableinheritance.html[EnableInheritance]"]  プロパティを公開します。子グリッド/バンドで固有の動作を構成することによって動作をオーバーライドでき、バンドはトップ レベルの動作をオーバーライドでき、行アイランドはバンド動作をオーバーライドできます。

=== 継承可能な動作

以下に WebHierarchicalDataGrid で使用できる継承可能な動作をリストします。

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.paging.html[ページング]"]
pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.sorting.html[並べ替え]"]
pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.filtering.html[フィルタリング]"]
pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.editingcore.html[EditingCore]"]

-  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.cellediting.html[CellEditing]"]

-  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.rowediting.html[RowEditing]"]

-  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.rowdeleting.html[RowDeleting]"]

-  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.rowadding.html[RowAdding]"]

-  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.roweditingtemplate.html[行編集テンプレート]"]

-  pick:[asp-net="link:webhierarchicaldatagrid-batch-updating.html[一括更新]"]
pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.rowselectors.html[RowSelectors]"]
pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.summaryrow.html[SummaryRow]"]
pick:[asp-net="link:webhierarchicaldatagrid-cell-merging.html[セルの結合]"]

=== 単一の動作

以下の動作は WebHierarchicalDataGrid のトップ レベルに限って設定でき、すべてのレベルに適用されます。

-  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.activation.html[アクティブ化]"]

-  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.selection.html[選択]"]

== 関連トピック

link:webhierarchicaldatagrid-auto-post-back-events.html[自動ポストバック イベント]

link:webhierarchicaldatagrid-activation.html[アクティブ化]

link:webhierarchicaldatagrid-editing.html[編集]

link:webhierarchicaldatagrid-enabling-paging.html[ページングを有効にする]

link:webhierachicaldatagrid-selection.html[選択]

link:webhierarchicaldatagrid-sorting.html[並べ替え]

link:webhierarchicaldatagrid-filtering.html[フィルタリング]

link:webhierarchicaldatagrid-summary-row.html[集計行]