////

|metadata|
{
    "name": "webhierarchicaldatagrid-binding-to-xml-data-source",
    "controlName": ["WebHierarchicalDataGrid"],
    "tags": ["Data Binding","Grids"],
    "guid": "{09F1F50D-6AD0-4B94-9ACC-937CA392973B}",  
    "buildFlags": [],
    "createdOn": "2009-01-10T14:30:45Z"
}
|metadata|
////

= Xml データ ソースにバインド

== 始める前に

WebHierarchicalDataGrid™ によって、兄弟バンドを持つ階層データにバインドすることができます。このコントロールは、個別のコンテナグリッドとして兄弟データを表示します。兄弟データと共に、親行は複数のデータアイランドを持つ場合があります。特定の行に属する固有のデータアイランドを参照するには、バンドの link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.band~datamember.html[DataMember] 名と行の link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.containergridrecord~rowislands.html[RowIslands] プロパティを使用するかキーをアクセサーとして使用します。

== 達成すること

兄弟データ バンドを持つ階層データを取得する XmlDataSource にバインドする方法を学習します。このサンプルは link:code-files-categoriesandproducts.html[CategoriesAndProducts.xml] ファイルを使用します。

== 次の手順を実行します

[start=1]
. ASP.NET Web ページを作成します。
[start=2]
. ツールボックスからページに ScriptManager コンポーネントをドラッグします。
[start=3]
. ツールボックスからページに WebHierarchicalDataGrid コントロールをドラッグします。
[start=4]
. ツールボックスから XmlDataSource コントロールをページにドラッグします。
[start=5]
. CategoriesAndProducts.xml データ ファイルを使用し、Categories データを取得するようにデータ パスを設定するために、XmlDataSource を設定します。

*HTML の場合:*

----
<asp:XmlDataSource ID="XmlDataSource1" runat="server" 
   DataFile="~/App_Data/CategoriesAndProducts.xml" XPath="/Categories/Category">
</asp:XmlDataSource>
----

[start=6]
. WebHierarchicalDataGrid の link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.gridcontrols.webhierarchicaldatagrid~datasourceid.html[DataSourceID] プロパティを XmlDataSource コントロールの ID である "XmlDataSource1" に設定します。
[start=7]
. ルート バンドの列スキーマを設定します。

*HTML の場合:*

----
<ig:WebHierarchicalDataGrid ID="WebHierarchicalDataGrid1" runat="server" 
   AutoGenerateBands=" AutoGenerateColumns=" 
   DataSourceID="XmlDataSource1" DefaultColumnWidth="" Key="Category" DataKeyFields="CategoryID">
<%-- Categories データの列を定義します --%>
   <Columns>
      <ig:BoundDataField DataFieldName="CategoryID" Key="CategoryID" Header-Text="CategoryID" />
      <ig:BoundDataField DataFieldName="CategoryName" Key="CategoryName" Header-Text="Category Name" />
      <ig:BoundDataField DataFieldName="Description" Key="Description" Header-Text="Description" />
   </Columns>
<%--行うこと:兄弟バンドを定義します --%>
</ig:WebHierarchicalDataGrid>
----

[start=8]
. 兄弟バンドを定義します。

*HTML の場合:*

----
<Bands>
<%-- 兄弟バンド 1 --%>
   <ig:Band AutoGenerateColumns=" DataMember="Product" DataKeyFields="ProductID">
      <Columns>
         <ig:BoundDataField DataFieldName="ProductID" Key="ProductID" Header-Text="ProductID" />
         <ig:BoundDataField DataFieldName="ProductName" Key="ProductName" Header-Text="Name" />
         <ig:BoundDataField DataFieldName="QuantityPerUnit" Key="QuantityPerUnit" Header-Text="Quantity Per Unit" />
         <ig:BoundDataField DataFieldName="UnitPrice" Key="UnitPrice" Header-Text="Unit Price" />
      </Columns>
   </ig:Band>
   </Bands>
----

[start=9]
. アプリケーションを実行します。WebHierarchicalDataGrid はネストされた兄弟行を持つ親行を表示します。

== 関連トピック

link:webhierarchicaldatagrid-binding-to-self-related-data.html[自己関係的なデータにバインド]