////

|metadata|
{
    "name": "webimagebutton-object-csom",
    "controlName": [],
    "tags": ["API","How Do I"],
    "guid": "{1308C5E1-0DE2-4DD6-89FF-061BF721453E}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebImageButton オブジェクト

== WebImageButton

サーバー上の WebImageButton クラスに関連する関数とメンバ変数を含むオブジェクト。このオブジェクトは、パラメータ ClientID または UniqueID を指定して、ig_getWebControlById 関数を呼び出すことで取得できます。

=== WebImageButton メソッド

[cols="a,a"]
|====
|*getAutoSubmit* 
|クリック イベントが発生する時にポストバックが起動するかどうかをチェックします。 

*戻り値*

ブール値。True - コントロールはクリック イベントでサーバーにポストバックを発生します。

|*getBackColorAt* 
|ボタンの特定の状態の背景色を取得します。 

*パラメータ*

_state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 

*戻り値*

文字列。背景色。

|*getBorderColorAt* 
|ボタンの特定の状態の境界線の色を取得します。 

*パラメータ*

_state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 

*戻り値*

文字列。ボーダー カラー。

|*getClientID* 
|サーバーの ClientID プロパティの値。 

*戻り値*

文字列。ClientID の値。

|*getDisplay* 
|表示がインラインまたはブロックかどうかを取得します。 

*戻り値*

文字列。サーバーの DisplayMode プロパティの値。

|*getElement* 
|オブジェクト。読み取り専用。WebImageButton を描出するメイン html 要素への参照。 

---- 
// 例：
var button = ig_getWebControlById("WebImageButton1");
if(button == null)  return;
var realWidthOfButton = button.getElement().offsetWidth;
---- 

*戻り値*

オブジェクト。html 要素への参照。

|*getElementAt* 
|WebImageButton の特定の部分を描出するメイン html 要素への参照を取得します。 

---- 
 // 例：
var button = ig_getWebControlById("WebImageButton1");
if(button == null)  return;
var span = button.getElementAt(3);
var widthOfText = span ? span.offsetWidth : 0;
var input = button.getElementAt(0);
var accessKey = input.accessKey; 
---- 

*パラメータ*

_flag_ 

数値。特定の要素のフラグ。取り得る値は次のとおりです。0 - INPUT、1 - メイン TABLE、2 - 外側 TABLE、3 - テキストの SPAN、4 - 画像の IMG、5 - メイン TD、6 - 上/右角の TD、7 - 下/左角の TD、8 - 下/右角の TD、9 - 内部 TABLE、11..30 - テーブル セルによって作られた角丸の TD。 

*戻り値*

オブジェクト。html 要素への参照または null。

|*getEnabled* 
|コントロールが有効かどうかをチェックします。 

*戻り値*

ブール値。True－コントロールは有効です。

|*getFocusable* 
|コントロールが入力フォーカスを取得できるかどうかをチェックします。 

*戻り値*

ブール値。True - コントロールはフォーカスを取得できます。

|*getForeColorAt* 
|ボタンの特定の状態の前景色を取得します。 

*パラメータ*

_state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 

*戻り値*

文字列。前景色。

|*getID* 
|ig_all に含まれる他のオブジェクトからこの WebImageButton を識別するのに使用される内部 ID の値。 

*戻り値*

文字列。内部 ID の値。

|*getImageAt* 
|ボタンの特定の状態の画像を含む url の名前を取得します。 

*パラメータ*

_state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 

*戻り値*

文字列。画像に使用される url の名前。

|*getRoundedImageAt* 
|ボタンの特定の状態の背景画像として使用される url の名前を取得します。 

*パラメータ*

_state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 

*戻り値*

文字列。背景画像。

|*getState* 
|ボタンの状態を取得します。 

*戻り値*

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。

|*getText* 
|ラベルのテキストを取得します。 

*戻り値*

文字列。ラベルのテキスト。

|*getUniqueID* 
|サーバーの UniqueID プロパティの値。 

*戻り値*

文字列。UniqueID の値。

|*getVisible* 
|コントロールが表示されるかどうかをチェックします。 

*戻り値*

ブール値。True－コントロールは表示されます。

|*hasFocus* 
|コントロールが入力フォーカスを持つかどうかをチェックします。 

*戻り値*

ブール値。True - コントロールがフォーカスを持ちます。

|*paint* 
|ボタンを再描画します。 

*パラメータ*

_value_ 

ブール値。省略可能。True - ボタンの古い状態に関係なくボタンを再描画します。False - ボタンの状態が変わった場合に限ってボタンを再描画します。

|*setBackColorAt* 
|ボタンの特定の状態の背景色を設定します。 

*パラメータ*

_value_ 

文字列。新しい背景色。 _state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 _persist_ 

ブール値。省略可能。サーバーに新しい値を保持するための要求。True - サーバーに新しい値を保持します。

|*setBorderColorAt* 
|ボタンの特定の状態の境界線の色を設定します。 

*パラメータ*

_value_ 

文字列。新しい境界線の色。 _state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 _persist_ 

ブール値。省略可能。サーバーに新しい値を保持するための要求。True - サーバーに新しい値を保持します。

|*setEnabled* 
|コントロールを有効または無効にします。新しい値はサーバーでも保持されます。 

*パラメータ*

_value_ 

ブール値。True－コントロールを有効化、False－無効化。

|*setFocus* 
|コントロールにフォーカスを設定します。

|*setForeColorAt* 
|ボタンの特定の状態の前景色を設定します。 

*パラメータ*

_value_ 

文字列。新しい前景色。 _state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 _persist_ 

ブール値。省略可能。サーバーに新しい値を保持するための要求。True - サーバーに新しい値を保持します。

|*setImageAt* 
|ボタンの特定の状態の画像を設定します。 

*パラメータ*

_value_ 

文字列。画像の新しい url。 _state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 _persist_ 

ブール値。省略可能。サーバーに新しい値を保持するための要求。True - サーバーに新しい値を保持します。

|*setRoundedImageAt* 
|ボタンの特定の状態の背景画像 url の名前を設定します。このプロパティは、サーバーの RoundedCorners プロパティが有効である場合に限って効果があります。 

*パラメータ*

_value_ 

文字列。新しい背景画像。 _state_ 

数値。ボタンの状態。取り得る値は次のとおりです。0 - 通常の状態、1 - フォーカスなしおよびマウスオーバー、2 - フォーカスおよびマウスオーバーなし、3 - フォーカスおよびマウスオーバー、4 - 押された状態、5 - 無効な状態。 _persist_ 

ブール値。省略可能。サーバーに新しい値を保持するための要求。True - サーバーに新しい値を保持します。

|*setText* 
|コントロールにテキスト ラベルを設定します。新しい値はサーバーでも保持されます。 

*パラメータ*

_value_ 

文字列。ラベルのテキスト。

|*setVisible* 
|コントロールを表示または非表示にします。新しい値はサーバーでは保持されません。 

*パラメータ*

_value_ 

ブール値。True－コントロールを表示、False－コントロールを非表示。

|====