////

|metadata|
{
    "name": "webimageviewer-api-overview",
    "controlName": ["WebImageViewer"],
    "tags": ["API","Layouts","Styling","Templating"],
    "guid": "{AFFC236F-9AFB-4AC8-980A-7AA53DE45D95}",  
    "buildFlags": [],
    "createdOn": "2008-12-01T21:04:15Z"
}
|metadata|
////

= API の概要

このセクションではコントロールに関連する各名前空間を示します。このコントロールでプログラムする間に使用するいくつかのキークラスも提供します。このページの名前空間とクラスは当社の API マニュアルに直接リンクします。

=== WebImageViewer 名前空間:

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols_namespace.html[Infragistics.Web.UI.ListControls]"]

=== キー クラス：

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.webimageviewer.html[WebImageViewer]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.captionarea.html[CaptionArea]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.animationobject.html[AnimationObject]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.listcontrols.scrollanimations.html[ScrollAnimations]"]