////

|metadata|
{
    "name": "webmaskeditor-data-modes-in-webmaskeditor",
    "controlName": ["WebMaskEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{A52BDD26-FBE2-40FA-B717-435BDD822A1B}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T16:06:34Z"
}
|metadata|
////

= WebMaskEditor のデータ モード

WebMaskEditor™ によって、入力マスク リテラルが値プロパティに含まれる必要があるかどうかを指定することができます。コントロールの  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webmaskeditor~datamode.html[DataMode]"]  プロパティを設定するだけで、この動作を構成できます。この動作は、以下のバリエーションに基づいて構成できます。

* リテラル文字を含む必要があるかどうか（日付値のスラッシュまたはダッシュなどのマスクの編集できない部分）。
* 必須の空のマスク位置が含まれるかどうか。
* オプションの空のマスク位置が含まれるかどうか。

Microsoft® Visual Studio® [プロパティ] ウィンドウを使用する、または以下のコードを使用することによって、DisplayMode プロパティを  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.maskdatamode.html[MaskDataMode]"]  列挙体のいずれかのメンバーに設定できます。

*Visual Basic の場合：*

----
WebMaskEditor1.DataMode = Infragistics.Web.UI.EditorControls.MaskDataMode.RawTextWithLiterals
----

*C# の場合：*

----
WebMaskEditor1.DataMode = Infragistics.Web.UI.EditorControls.MaskDataMode.RawTextWithLiterals;
----