////

|metadata|
{
    "name": "webpercenteditor-using-display-factor-in-webpercenteditor",
    "controlName": ["WebPercentEditor"],
    "tags": ["Editing","How Do I","Styling"],
    "guid": "{6502F81D-66DA-485D-ACB8-4276560D5B64}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebPercentEditor で表示係数を使用

WebPercentEditor™ によって、コントロールで値を乗じる係数を設定することが可能となり、エディターに実際のテキストとして表示します。たとえば、表示係数が 100 で、エンドユーザーがエディターに 80 を入力すると（ pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~text.html[Text]"]  プロパティで反映される）、コントロールの  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~value.html[Value]"]  プロパティは 0.8 になります。コントロールの  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~displayfactor.html[DisplayFactor]"]  プロパティを設定するだけで表示係数を設定することができます。デフォルトでこのプロパティは 100 に設定されます。

*Visual Basic の場合：*

----
WebPercentEditor1.DisplayFactor = 10
----

*C# の場合：*

----
WebPercentEditor1.DisplayFactor = 10;
----