////

|metadata|
{
    "name": "webpercenteditor-setting-minimum-and-maximum-values-for-webpercenteditor",
    "controlName": ["WebPercentEditor"],
    "tags": ["Editing","Error Handling","How Do I","Styling"],
    "guid": "{EDA893AB-38C9-482F-AFFE-336C3B248ED4}",  
    "buildFlags": [],
    "createdOn": "2009-03-06T13:48:57Z"
}
|metadata|
////

= WebPercentEditor の最小値と最大値を設定

WebPercentEditor™ によって、コントロールの  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~minvalue.html[MinValue]"]  および  pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.editorcontrols.webnumericeditor~maxvalue.html[MaxValue]"]  プロパティを設定するだけで、エンドユーザーがエディターに入力できる値の範囲を設定することができます。エンドユーザーが最大値より大きいパーセントを入力すると、エディターはその値を最大値に設定します。同様に、エンドユーザーが最小値より小さいパーセントを入力すると、エディターはその値を最小値に設定します。

Microsoft® Visual Studio® [プロパティ] ウィンドウを使用する、または以下のコードを使用することによって、MinValue プロパティと MaxValue プロパティを設定できます:

*Visual Basic の場合：*

----
WebPercentEditor1.MinValue = 10
WebPercentEditor1.MaxValue = 95
----

*C# の場合：*

----
WebPercentEditor1.MinValue = 10;
WebPercentEditor1.MaxValue = 95;
----

*JavaScript の場合：*

----
var Editor = $find("WebPercentEditor1");
Editor.set_minValue(10);
Editor.set_maxValue(95);
----