////

|metadata|
{
    "name": "webschedule-utility-functions-csom",
    "controlName": [],
    "tags": ["API","How Do I","Scheduling"],
    "guid": "{9C67080E-6705-4D7C-8EED-09E81D73AE69}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= WebSchedule ユーティリティ関数

== ユーティリティ関数

=== 概要

ここで説明するユーティリティ関数は、WebSchedule コントロールの JavaScript コードで使用されます。ユーティリティ関数を公開し解説するのは、開発者が可能な限り多くのロジックをクライアント マシン上に実装することで、パフォーマンスと機能性の両面で性能を引き出せるようにすることを意図しています。

function ig_getWebControlById(id)*

すべてのスケジュール コントロール（WebScheduleInfo、WebDayView、WebCalendarView、WebMonthView）で機能します。

function ig_getWebCalendarViewById(id);*

メインの WebCalendarView 要素の ID に基づいて、WebCalendarView オブジェクトを取得します。

function ig_getWebScheduleInfoById(id);*

メインの WebScheduleInfo 要素の ID に基づいて、WebScheduleInfo オブジェクトを取得します。

function ig_getWebMonthViewById(id);*

メインの WebMonthView 要素の ID に基づいて、WebMonthView オブジェクトを取得します。

function ig_getWebDayViewById(id);*

メインの WebDayView 要素の ID に基づいて、WebDayView オブジェクトを取得します。