////

|metadata|
{
    "name": "webschedulegenericdataprovider-webschedulegenericdataprovider",
    "controlName": [],
    "tags": ["Getting Started","How Do I"],
    "guid": "{0137C36F-3F2A-491F-8B46-EB194C22A5FC}",  
    "buildFlags": [],
    "createdOn": "2009-12-10T16:35:25Z"
}
|metadata|
////

= WebScheduleGenericDataProvider

WebScheduleGenericDataProvider™ コンポーネントの紹介については以下のリンクをクリックしてください。

* link:webschedulegenericdataprovider-about-webschedulegenericdataprovider.html[WebScheduleGenericDataProvider について] -- WebScheduleGenericDataProvider コンポーネントの機能と、それをアプリケーション内で使用することの利点について説明しています。
* link:webschedulegenericdataprovider-webschedulegenericdataprovider-smart-tag.html[WebScheduleGenericDataProvider スマート タグ] -- WebScheduleGenericDataProvider スマート タグで利用可能な機能性について説明しています。

WebScheduleGenericDataProvider コンポーネントは、コントロールおよびコンポーネントの WebSchedule™ グループの一部です。複数の WebSchedule コントロールおよびコンポーネント（WebCalendarView™、WebDayView™）に共通する概要/タスクベースの情報を収めているセクションを探している場合には、以下のリンクをクリックします。

link:web-webschedule.html[WebSchedule]