////
|metadata|
{
    "name": "webschedule-add-an-activity-to-the-database",
    "controlName": ["WebSchedule"],
    "tags": ["How Do I","Scheduling"],
    "guid": "{EA9AB1D2-1BBA-4890-A4F7-2C182F88D1A1}",
    "buildFlags": [],
    "createdOn": "2005-07-09T00:00:00Z"
}
|metadata|
////

= アクティビティをデータベースに追加

サーバー側のコードビハインドで、永続性のためにデータベースのアクティビティ テーブルに新しい pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule.activity.html[アクティビティ]"] を追加することができます。この例は、 link:webschedule-create-an-activity-using-code.html[「コードでアクティビティを作成する方法」]のトピックを使用します。データベースにアクティビティを追加するには、以下の 3 つを必要とします。

[start=1]
. アクティビティの具体的なインスタンス（例: pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule.appointment.html[Appointment]"]  オブジェクト）
[start=2]
. このアクティビティを所有、構成、またはこのアクティビティが関連する  pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule.resource.html[リソース]"] （人または物）。
[start=3]
. WebScheduleDbProvider クラスから派生したデータ プロバイダ。

ASP.NET ボタンを「AddButton1」という名前の WebForm に追加し、その Click イベントを処理して新しい Appointment オブジェクトを作成します。

データプロバイダの  pick:[asp-net="link:{ApiPlatform}webui.webscheduledataprovider{ApiVersion}~infragistics.webui.data.webscheduledbprovider~addactivity.html[AddActivity]"]  メソッドに未割り当てのリソース（またはその他の関連リソース）とともにこれを渡します。

*Visual Basic の場合：* 

---- 
Imports Infragistics.WebUI.Shared 
Imports Infragistics.WebUI.WebSchedule 
... 
Private Sub AddButton1_Click(ByVal sender As Object, _ 
	ByVal e As EventArgs) Handles AddButton1.Click 
	' Appointment オブジェクトを作成します。 
	Dim appt As Appointment = Me.CreateAppointment() 
	' Appointment をデータベースに追加し、未割り当ての 
	' リソースと関連付けます。 
	Me.WebScheduleSqlClientDataProvider1.AddActivity( _ 
	 appt, _ 
	 Me.WebScheduleInfo1.VisibleResources.UnassignedResource) 
End Sub
---- 

*C# の場合：*

---- 
using Infragistics.WebUI.Shared; 
using Infragistics.WebUI.WebSchedule; 
... 
private void AddButton1_Click(object sender, EventArgs e) 
{ 
	// Appointment オブジェクトを作成します。 
	Appointment appt = this.CreateAppointment(); 
	// Appointment をデータベースに追加し、未割り当ての 
	// リソースと関連付けます。 
	this.WebScheduleSqlClientDataProvider1.AddActivity( 
	 appt, 
	 this.WebScheduleInfo1.VisibleResources.UnassignedResource); 
}
---- 

*注：* この例は Microsoft SQL Server データプロバイダが使用されていることを示していますが、これは OLE DB を含む WebScheduleDbProvider から派生した任意のデータプロバイダと連動します。 

== 関連トピック

pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule_namespace.html[WebSchedule 名前空間]"]

pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule.webscheduleinfo.html[WebScheduleInfo クラス]"]

pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule.webdayview.html[WebDayView クラス]"]

pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule.webmonthview.html[WebMonthView クラス]"]

pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule.appointment.html[Appointment クラス]"]

pick:[asp-net="link:{ApiPlatform}webui.webschedule{ApiVersion}~infragistics.webui.webschedule.activity.html[Activity オブジェクト]"]