////

|metadata|
{
    "name": "webschedule-csom-overview",
    "controlName": ["WebSchedule"],
    "tags": ["API"],
    "guid": "{C22CEA99-404C-434A-95EF-810543580F49}",  
    "buildFlags": [],
    "createdOn": "0001-01-01T00:00:00Z"
}
|metadata|
////

= CSOM 概要

WebSchedule は、クライアント側の JavaScript プログラミング環境に強固なオブジェクト モデルを提供します。クライアント サイド オブジェクト モデル（CSOM）は、十分な機能を備えた JavaScript オブジェクト、イベント、ユーティリティ関数から構成され、開発者はサーバー側でポストバックしなくても、WebSchedule コントロールおよびコンポーネントに関連する重要な機能単位をプログラムできます。

一般的に、オブジェクト モデルは、サーバー上の場合と同じようにオブジェクト モデルから直接派生しています。プロパティ名、イベント、パラメータ、戻り値の意味は、サーバー上のそれらとほとんど同じです。ただし、注が付けられている一部のプロパティはクライアント上では読み取り専用です。これらのプロパティは情報提供のみを目的としています。したがって修正できません。

以下は WebSchedule コントロールの CSOM 参照情報へのリンクです。

link:webschedule-utility-functions-csom.html[WebSchedule ユーティリティ関数]

link:webschedule-activity-object-csom.html[Activity オブジェクト]

link:webschedule-activities-collection-csom.html[Activities コレクション]

link:webschedule-day-object-csom.html[Day オブジェクト]

link:webschedule-progressindicator-object-csom.html[ProgressIndicator オブジェクト]

link:webschedule-reminders-collections-csom.html[Reminders コレクション]

link:webschedule-reminder-object-csom.html[Reminder オブジェクト]