////

|metadata|
{
    "name": "webschedule-reminders",
    "controlName": ["WebSchedule"],
    "tags": [],
    "guid": "{261EC5B2-0D47-46AC-81C4-F31515BC2F17}",  
    "buildFlags": [],
    "createdOn": "2005-01-08T00:00:00Z"
}
|metadata|
////

= アラーム

WebSchedule は、そのビューのいずれかからアラーム通知をサポートします。近い将来発生するアクティビティとすでに経過したアクティビティに Web ダイアログが表示されます。ユーザーはアラームを解除する、基本のアクティビティを編集する、または再度アラームを起動する期間（ _再通知_ ）を設定することができます。

アラームの間に表示される Web ダイアログの個々の視覚的な側面をスタイルできます。たとえば、アプリケーションにより相応しいフォントや背景色を変更することができます。

WebScheduleInfo コントロール、個々のリソース、または個々のアクティビティによって管理されているすべての WebSchedule ビューでアラームをオフにすることができます。その他のリソースのスケジュール情報を確認するユーザーはアラームを受け取ることに関心がないため、WebScheduleInfo コントロールはログオンしたユーザーをアプリケーションのユーザー認証に結び付けるという概念をサポートします。アクティブなリソースの名前がログオンしたユーザーの名前と一致しない時には、アラームが表示されません。

Web 環境では、アラームの提供はプル モデルに基づいた「最善の」努力です。Web ダイアログには、Web サーバーへの以下のポストバックが表示されます。ブラウザの定期的なポストバックに失敗すると、アラームは正確に時間どおりに表示されません。

* link:webschedule-checking-for-reminders.html[アラームのチェック]
* link:webschedule-conditions-for-displaying-the-reminder-dialog-box.html[[アラーム] ダイアログ ボックスを表示するための条件]