////

|metadata|
{
    "name": "websplitter-api-overview",
    "controlName": ["WebSplitter"],
    "tags": ["API"],
    "guid": "{1089A4EC-BBC8-44D4-AF38-0424B2B557FC}",  
    "buildFlags": [],
    "createdOn": "2008-12-01T21:09:33Z"
}
|metadata|
////

= API の概要

このセクションではコントロールに関連する各名前空間を示します。このコントロールでプログラムする間に使用するいくつかのキークラスも提供します。このページの名前空間とクラスは当社の API マニュアルに直接リンクします。

=== WebSplitter 名前空間:

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols_namespace.html[Infragistics.Web.UI.LayoutControls]"]

=== キー クラス：

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols.websplitter.html[WebSplitter]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols.splitterpane.html[SplitterPane]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols.splitterbar.html[SplitterBar]"]

pick:[asp-net="link:{ApiPlatform}web{ApiVersion}~infragistics.web.ui.layoutcontrols.contentpane.html[ContentPane]"]