////

|metadata|
{
    "name": "webupload-accessibility compliance",
    "controlName": ["WebUpload"],
    "tags": ["Section 508","Selection"],
    "guid": "accab5ff-c1b4-4666-8131-ed80a6d824e7",  
    "buildFlags": [],
    "createdOn": "2011-05-26T15:01:16.0829367Z"
}
|metadata|
////

= アクセシビリティの遵守 (WebUpload)

== アップロード アクセシビリティの遵守

{ProductName} コントロールおよびコンポーネントはすべて、1973 年のリハビリテーション法第 508 条第 1194 部 22 条を遵守しています。表 1 には、コントロールに関連する第 1194.22 部の具体的な規則が含まれます。また、WebUpload が各規則にどのように準拠するかについて詳細に示します。

各アクセシビリティ規則の要件を満たすため、場合によっては、特定のプロパティを設定してコントロールを操作する必要がありますが、場合によってはコントロールが開発者に代わって処理してくれます。

*注:* WebUpload にはクライアント側に多くのロジックがあるため、規則の一部がサポートされていなかったり、制約があると記載されています。

表 1: 第 508 条の法令遵守についての説明

[options="header", cols="a,a"]
|====
|規則|法令遵守

|(c)
|クライアント側イベントを使用すると、現在の状態を反映するいかなるコントロールの DOM 要素の属性をユーザーは変更できます。

|(d)$$*$$
|コントロールのマークアップは、関連付けられたスタイル シートなしでは読み取ることができません。これはクライアント側コントロールであり、CSS の規則に依存するからです。

|(l)
|コントロールのスクリプトがページ マークアップを変更している時、規則 (c) で説明されている属性のために新しく作成されたコンテンツはスクリーン リーダーに準拠します。

|(n)
|デフォルトでは、コントロールはページのタブのシーケンスに関与します。TAB キーを使用することによって、コントロールとその要素をナビゲートできます。

|(o)
|(n) で述べたいくつかのナビゲーション キーでこれを達成できます。

|(p)
|ファイルのアップロード中、プログレス バーから現在のアップロード状況を受け取ります。

|====

$$*$$ - コントロールの制約

== 関連リンク

link:webupload-overview.html[WebUpload の概要]