////

|metadata|
{
    "name": "webvideoplayer-accessibility-compliance",
    "controlName": ["WebVideoPlayer"],
    "tags": ["Section 508"],
    "guid": "280f7358-0106-4153-b1e0-45f502905a46",  
    "buildFlags": [],
    "createdOn": "2011-06-01T08:11:10.9442388Z"
}
|metadata|
////

= WebVideoPlayer アクセシビリティ規則

弊社の ASP.NET コントロールおよびコンポーネントはすべて、1973 年のリハビリテーション法第 508 条第 1194 部 22 条を遵守しています。表 1 には、コントロールに関連する第 1194.22 部の具体的な規則が含まれます。また、ビデオ プレーヤーが各規則にどのように準拠するかについて詳細に示します。

各アクセシビリティ規則の要件を満たすため、場合によっては、特定のプロパティを設定してコントロールを操作する必要がありますが、場合によってはコントロールが開発者に代わって処理してくれます。

*注:* jQuery コントロールはクライアント専用であるため、規則の一部がサポートされていなかったり、制約があると記載されています。

*表 1: 第 508 条の法令遵守についての説明*

[options="header", cols="a,a"]
|====
|規則|規則を遵守する方法

|(c)
|クライアント側イベントを使用すると、現在の状態を反映するいかなるコントロールの DOM 要素の属性をユーザーは変更できます。

|(d)$$*$$
|コントロールのマークアップは、関連付けられたスタイル シートなしでは読み取ることができません。これはクライアント側コントロールであり、CSS の規則に依存するからです。

|(j)$$*$$
|コントロールは 画面のフリッカーが生じないように設計されています。ただし、再生されるビデオにフリッカーに似た特定のエフェクトが含まれる場合があります。これをこのコントロールが制限したり、いかなる方法で再生を中止しません。

|(l)
|コントロールのスクリプトがページ マークアップを変更している時、規則 (c) で説明されている属性のために新しく作成されたコンテンツはスクリーン リーダーに準拠します。

|(n)
|jQuery Video Player はページのタブ シーケンスに加わり、マウスのクリックを含みフォーカスを受け取ります。 

右矢印 - 前に再生されます（スライダーがフォーカスを取得している時）。 

左矢印 - 後ろに再生されます（スライダーがフォーカスを取得している時）。 

SPACE - 現在の状態に基づいてビデオを一時停止または再生します。 

ESC - 全画面表示を終了します。 

TAB - 再生コントロールを移動して各コントロール ボタンにフォーカスを設定します。インフラジスティックスの再生コントロールが使用される時に限り機能します。埋め込みブラウザー コントロールはキーボード ナビゲーションをサポートしません。

|====

$$*$$ - コントロールの制約