////

|metadata|
{
    "name": "webvideoplayer-known-issues",
    "controlName": ["WebVideoPlayer"],
    "tags": ["Known Issues"],
    "guid": "a77cbcc0-6b9f-435d-b336-93d9e35112d7",  
    "buildFlags": [],
    "createdOn": "2011-06-01T08:11:43.0664507Z"
}
|metadata|
////

= WebVideoPlayer 既知の問題

== 既知の問題と制限

ブラウザーのサポートが完全でないためや jQuery のバグのために存在する既知の問題と制限を以下にリストします。

* Microsoft® Internet Explorer™ 9 の場合

** ビデオを一時停止して再び再生を開始する時に最初にミュートだった場合には、ビデオの音が少し再生されます。
** ポスター画像は Internet Explorer 9 で表示されません。ビデオ ソースがビデオ タグで読み込まれない場合に限り表示されます。ブラウザーには、代わりにポスターとして最初のビデオ フレームが表示されます。
** jQuery UI バージョン 1.8.5 以前を使用していると、ボリューム スライダーのハンドルをドラッグしてもスムーズに動作しません。この問題は、バージョン 1.8.6 以降では確認されません。

* Google® Chrome™ の場合

** ユーザーが標準画面から全画面表示にまたはその逆に切り替えると、カスタム ブラウザー コントロールは縮小および展開して、フリッカー効果のように表示します。これは、Chrome 固有のブラウザー レンダリングの問題です。

* Opera™ 11.10 以前の場合

** バッファーされた進行状況は Opera 11.10 以前では更新しません。

* jQuery 1.4.2 以前の場合

** ‘400’ のような文字列で幅/高さを指定しても、jQuery バージョン 1.4.3 以前では動作しません。400 のような数字、または「400px」の中にある「px」が付いた文字列のいずれかを使用する必要があります。

* コントロール レイアウト

** コントロールがテーブル コンテナーに配置される時、カスタムの Infragistics コントロールはテーブルのデフォルト プロパティの影響を受けます。この問題を解決するには、「border-spacing: 0;」を親に配置する必要があります。

== 関連トピック

link:webvideoplayer-overview.html[igVideoPlayer の概要]