////

|metadata|
{
    "name": "webwordexporter-about-webwordexporter",
    "controlName": ["WebWordExporter"],
    "tags": ["Exporting","Grids","Printing"],
    "guid": "5f92d63c-7250-4251-87ab-1127f9148425",  
    "buildFlags": [],
    "createdOn": "2011-10-26T12:54:04.5659708Z"
}
|metadata|
////

= WebWordExporter について

このトピックは、WebWordExporter™ コンポーネントを紹介します。

== はじめに

WebWordExporter は WebDataGrid™ または WebHierarchicalDataGrid™ 全体を Word ファイルにエクスポートできるエクスポート機能を備えたコンポーネントです。

Export メソッドは総合的なエクスポート機能を実装しています。エクスポートをカスタマイズするイベントがいくつかあります。これらのイベントの多くは、行、ヘッダー、セルなどの特定のオブジェクトがエクスポートされる直前やオブジェクトがエクスポートされた後に起動します。エクスポート全体の開始と終了時に起動するイベントもあります。また、グリッドの行のレイアウトをエクスポートする前に変更できる event OnRowExporting があります。また、そのイベントはキャンセルでき、キャンセルされたときは行はエクスポートされたドキュメントに含まれません。

WebWordExporter コントロールは、それらのグリッドを順次エクスポートするため Web コントロールのグリッドのリストを渡すなど、Export メソッドのオーバーロードをいくつかサポートします。

ドキュメントを作成して、コンテンツを入れる場合、このドキュメントはパラメーターとして Export メソッドに渡すこともできます。その場合、Exporter はドキュメントのコンテンツの後ろにグリッド データを付加します。

== 機能

* 異なるエクスポート モード - エクスポートされたファイルが提示される方法を定義します。ファイルは自動的にダウンロードするようブラウザーに送信したり、ドキュメント インスタンスに単に保存したりできるため、結果をどうするのかを決定します。現在グリッドで表示されているデータのみエクスポートすることもできます。
* スタイル エクスポート サポート - スタイルもエクスポートできるため、アプリケーションのルック アンド フィールを保持したり、データを単純な表形式にエクスポートしたりします。
* エクスポート出力のカスタマイズ可能なページ レイアウト

== 関連トピック

以下は、その他の役立つトピックです。

* link:webwordexporter-getting-started-with-webwordexporter.html[WebWordExporter のセットアップ]
* link:webwordexporter-api-overview.html[API の概要]