////

|metadata|
{
    "name": "word-creating-word-document-using-object-model-approach",
    "controlName": [],
    "tags": [],
    "guid": "4e71e7b9-4fc9-4f8a-8414-6aca8cfc24eb",  
    "buildFlags": [],
    "createdOn": "2012-04-19T07:48:33.9957352Z"
}
|metadata|
////

= オブジェクト モデル アプローチで Word 文書を作成

このトピックは、オブジェクト モデル アプローチを使用して Microsoft® Word® ドキュメントおよびレイアウト要素を作成する方法を説明します。

== 概要

トピックは以下のとおりです。

* <<CreateSimpleDoc,単純な Word 文書の作成>>
* <<AddHyperlink,ハイパーリンクの追加>>
* <<AddPic,ピクチャの追加>>

** <<AddAnchPic,アンカー固定した画像の追加>>
** <<AddInlinePic,インライン画像の追加>>

* <<HeaderFooter,ヘッダーとフッターの設定>>

** <<Header,ヘッダーの追加と設定>>
** <<Footer,フッターの追加と設定>>

* <<ExCode,コード例: 完全なコード例>>
* <<RelatedTopics,関連トピック>>

[[CreateSimpleDoc]]
== 単純な Word 文書の作成

Word 文書全体は、 link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.document.html[Document] クラスでカプセル化されます。Document クラスはオブジェクト階層のルート レベルのエンティティで、この下にすべての他のオブジェクトがグループ化されています。段落およびテーブルなどのブロック レベルのコンテンツのコンテナーとして使用されます。ブロック レベルのコンテンツは、 link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.document~contentblocks.html[ContentBlocks] コレクション内に含まれます。

ドキュメントの個々のパラグラフは、 link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.paragraph.html[Paragraph] クラスでカプセル化されます。Paragraph クラスは、 link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.paragraph~contentruns.html[ContentRuns] コレクションを公開します。これはコンテンツをパラグラフに追加する方法を提供します。

Word 文書を生成するには、Document クラスのインスタンスを作成し、公開されているプロパティとメソッドを使用して作業し、そして link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.document~save.html[Save] メソッドを呼び出します。

Author、Title、Subject などの Word 文書のさまざまなプロパティは、 link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.document~documentproperties.html[DocumentProperties] プロパティを使用して設定できます。Office ボタンをクリックして、[準備] > [プロパティ] セクションを指定することによって、Word 2007 でこれらの情報にアクセスできます。Word 2010 で同様に、[ファイル] タブをクリックすることによって、Backstage ビューの右側からドキュメント プロパティにアクセスできます。

*C# の場合:*

----
using Infragistics.Documents.Word;
string documentName = @"C:\TestWordDOMDoc.docx";
Document doc = new Document();
// タイトル、著者などのドキュメント プロパティを設定します
doc.DocumentProperties.Title = "Sample Document";
doc.DocumentProperties.Author = string.Format("Infragistics.{0}", SystemInformation.UserName);
Infragistics.Documents.Word.Font font = doc.CreateFont();
font.Bold = true;
font.Size = 15;
font.Underline = Underline.Double;
// 段落をドキュメントに追加します
Paragraph para1 = doc.ContentBlocks.AddParagraph();
para1.ContentRuns.AddTextRun("Sample Word Document with Hyperlinks,Images,Headers and Footers", font);
----

*Visual Basic の場合:*

----
Imports Infragistics.Documents.Word
Dim documentName As String = "C:\TestWordDOMDoc.docx"
Dim doc As New Document()
' タイトル、著者などのドキュメント プロパティを設定します
doc.DocumentProperties.Title = "Sample Document"
doc.DocumentProperties.Author = String.Format("Infragistics.{0}", SystemInformation.UserName)
Dim font As Infragistics.Documents.Word.Font = doc.CreateFont()
font.Bold = True
font.Size = 15
font.Underline = Underline.[Double]
' 段落をドキュメントに追加します
Dim para1 As Paragraph = doc.ContentBlocks.AddParagraph()
para1.ContentRuns.AddTextRun("Sample Word Document with Hyperlinks,Images,Headers and Footers", font)
----

[[AddHyperlink]]
== ハイパーリンクを Word 文書に追加

Infragistics Word ライブラリはハイパーリンクをサポートします。 link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.contentrunscollection~addhyperlink.html[AddHyperlink] メソッドは、TextHyperlink を関連付けられたパラグラフに追加します。

*C# の場合:*

----
using Infragistics.Documents.Word;
// 段落をドキュメントに追加します
Paragraph para2 = doc.ContentBlocks.AddParagraph();
para2.ContentRuns.AddTextRun("Hyper link:  ");
// ハイパーリンクを追加します
para2.ContentRuns.AddHyperlink("http://www.infragistics.com", "Infragistics Inc.");
----

*Visual Basic の場合:*

----
Imports Infragistics.Documents.Word
' 段落をドキュメントに追加します
Dim para2 As Paragraph = doc.ContentBlocks.AddParagraph()
para2.ContentRuns.AddTextRun("Hyper link:  ")
' ハイパーリンクを追加します
para2.ContentRuns.AddHyperlink("http://www.infragistics.com", "Infragistics Inc.")
----

[[AddPic]]
== ピクチャの追加

[[AddAnchPic]]
== アンカー固定した画像の追加

link:{ApiPlatform}webui.documents.io{ApiVersion}~infragistics.documents.word.anchoredpicture.html[AnchoredPicture] クラスは、ドキュメント内の固有の場所にアンカー固定される画像をカプセル化します。 link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.anchorscollection~addanchoredpicture.html[AddAnchoredPicture] メソッドは、アンカー固定された画像を関連付けられたパラグラフに追加します。

*C# の場合:*

----
using Infragistics.Documents.Word;
// 画像を取得します
Image img = Image.FromFile(@"..\..\Ballon_New_Year.jpg");
// 段落をドキュメントに追加します
Paragraph para3 = doc.ContentBlocks.AddParagraph();
para3.ContentRuns.AddTextRun("Anchored Picture: An Anchored picture or image is one that is anchored to a specific location within the document.Unlike an inline picture, which moves along with adjacent content, an Anchored Picture remains at a fixed location within the paragraph, with adjacent text flowing around it.");
// アンカー固定した画像を作成します
AnchoredPicture anchPic = doc.CreateAnchoredPicture(img);
// アンカー固定した画像の画像アウトライン プロパティを指定します
anchPic.AlternateTextDescription = "Word Image";
anchPic.Outline.Color = Color.Brown;
anchPic.Outline.Style = PictureOutlineStyle.Single;
anchPic.Outline.LineWidth = 1;
// アンカー固定した画像をパラグラフのアンカー セクションに追加します
para3.Anchors.AddAnchoredPicture(anchPic);
----

*Visual Basic の場合:*

----
Imports Infragistics.Documents.Word
' 画像を取得します
Dim img As Image = Image.FromFile("..\..\Ballon_New_Year.jpg")
' 段落をドキュメントに追加します
Dim para3 As Paragraph = doc.ContentBlocks.AddParagraph()
para3.ContentRuns.AddTextRun("Anchored Picture: An Anchored picture or image is one that is anchored to a specific location within the document.Unlike an inline picture, which moves along with adjacent content, an Anchored Picture remains at a fixed location within the paragraph, with adjacent text flowing around it.")
' アンカー固定した画像を作成します
Dim anchPic As AnchoredPicture = doc.CreateAnchoredPicture(img)
' アンカー固定した画像の画像アウトライン プロパティを指定します
anchPic.AlternateTextDescription = "Word Image"
anchPic.Outline.Color = Color.Brown
anchPic.Outline.Style = PictureOutlineStyle.[Single]
anchPic.Outline.LineWidth = 1
' アンカー固定した画像をパラグラフのアンカー セクションに追加します
para3.Anchors.AddAnchoredPicture(anchPic)
----

[[AddInlinePic]]
== インライン画像の追加

link:{ApiPlatform}webui.documents.io{ApiVersion}~infragistics.documents.word.inlinepicture.html[InlinePicture] クラスは、画像をカプセル化し、ドキュメント内のテキスト コンテンツと共にインライン表示します。 link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.contentrunscollection~addinlinepicture.html[AddInlinePicture] メソッドは、インライン画像を関連付けられたパラグラフに追加します。

*C# の場合:*

----
using Infragistics.Documents.Word;
// 画像を取得します
Image img = Image.FromFile(@"..\..\Ballon_New_Year.jpg");
// 段落をドキュメントに追加します
Paragraph para4 = doc.ContentBlocks.AddParagraph();
para4.ContentRuns.AddTextRun("Inline Picture: An inline picture moves with the adjacent content");
// インライン画像を作成します
InlinePicture inlinePic = doc.CreateInlinePicture(img);
inlinePic.AlternateTextDescription = "Word Image";
// インライン画像をパラグラフのコンテンツ セクションに追加します
para4.ContentRuns.AddInlinePicture(inlinePic);
----

*Visual Basic の場合:*

----
Imports Infragistics.Documents.Word
' 画像を取得します
Dim img As Image = Image.FromFile("..\..\Ballon_New_Year.jpg")
' 段落をドキュメントに追加します
Dim para4 As Paragraph = doc.ContentBlocks.AddParagraph()
para4.ContentRuns.AddTextRun("Inline Picture: An inline picture moves with the adjacent content")
' インライン画像を作成します
Dim inlinePic As InlinePicture = doc.CreateInlinePicture(img)
inlinePic.AlternateTextDescription = "Word Image"
' インライン画像をパラグラフのコンテンツ セクションに追加します
para4.ContentRuns.AddInlinePicture(inlinePic)
----

link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.section.html[Section] クラスは、改ページ プロパティおよびドキュメント セクションのヘッダー/フッター コンテンツをカプセル化します。

[[HeaderFooter]]
== ヘッダーとフッターの設定

[[Header]]
== ヘッダーの追加と設定

以下のコード例は、すべてのページのヘッダー セクションにテキストと画像を表示する方法を示します。

*C# の場合:*

----
using Infragistics.Documents.Word;
// 段落をドキュメントに追加します
Paragraph para5 = doc.ContentBlocks.AddParagraph();
// テキストをパラグラフに追加します
Section sec = doc.Sections.Add(para5);
// ヘッダー
Paragraph headerPara = sec.HeaderAllPages.ContentBlocks.AddParagraph();
// ヘッダー テキスト配置は、右に設定されます
headerPara.Properties.Alignment = ParagraphAlignment.Right;
// ヘッダーに表示するアンカー固定される画像を作成します
AnchoredPicture headeranchPic = doc.CreateAnchoredPicture(img);
// ヘッダーにアンカー固定された画像を表示します
headerPara.Anchors.AddAnchoredPicture(headeranchPic);
// ヘッダーにテキストを表示します
headerPara.ContentRuns.AddTextRun("This is a header");
----

*Visual Basic の場合:*

----
Imports Infragistics.Documents.Word
' 段落をドキュメントに追加します
Dim para5 As Paragraph = doc.ContentBlocks.AddParagraph()
' テキストをパラグラフに追加します
Dim sec As Section = doc.Sections.Add(para5)
' ヘッダー
Dim headerPara As Paragraph = sec.HeaderAllPages.ContentBlocks.AddParagraph()
' ヘッダー テキスト配置は、右に設定されます
headerPara.Properties.Alignment = ParagraphAlignment.Right
' ヘッダーに表示するアンカー固定される画像を作成します
Dim headeranchPic As AnchoredPicture = doc.CreateAnchoredPicture(img)
' ヘッダーにアンカー固定された画像を表示します
headerPara.Anchors.AddAnchoredPicture(headeranchPic)
' ヘッダーにテキストを表示します
headerPara.ContentRuns.AddTextRun("This is a header")
----

[[Footer]]
== フッターの追加と設定

link:{ApiPlatform}webui.documents.word{ApiVersion}~infragistics.documents.word.contentrunscollection~addpagenumberfield.html[AddPageNumberField] メソッドは、PageNumberField を関連付けられたパラグラフに追加します。

*C# の場合:*

----
using Infragistics.Documents.Word;
// 段落をドキュメントに追加します
Paragraph para5 = doc.ContentBlocks.AddParagraph();
// 指定されたパラグラフで改ページを定義するセクションを追加します
Section sec = doc.Sections.Add(para5);
// フッター
Paragraph footerPara = sec.FooterAllPages.ContentBlocks.AddParagraph();
// フッター テキスト配置は、右に設定されます
footerPara.Properties.Alignment = ParagraphAlignment.Right;
// フッターにテキストを表示します
footerPara.ContentRuns.AddTextRun("This is a footer");
// ページ番号をフッターに追加します
footerPara.ContentRuns.AddPageNumberField(PageNumberFieldFormat.Ordinal);
----

*Visual Basic の場合:*

----
Imports Infragistics.Documents.Word
' 段落をドキュメントに追加します
Dim para5 As Paragraph = doc.ContentBlocks.AddParagraph()
' 指定されたパラグラフで改ページを定義するセクションを追加します
Dim sec As Section = doc.Sections.Add(para5)
' フッター
Dim footerPara As Paragraph = sec.FooterAllPages.ContentBlocks.AddParagraph()
' フッター テキスト配置は、右に設定されます
footerPara.Properties.Alignment = ParagraphAlignment.Right
' フッターにテキストを表示します
footerPara.ContentRuns.AddTextRun("This is a footer")
' ページ番号をフッターに追加します
footerPara.ContentRuns.AddPageNumberField(PageNumberFieldFormat.Ordinal)
----

[[ExCode]]
== コード例: 完全なコード例

以下は、このトピックの例で使用される完全なコードです。

*C# の場合:*

----
using Infragistics.Documents.Word;
string documentName = @"C:\TestWordDOMDoc.docx";
Document doc = new Document();
// タイトル、著者などのドキュメント プロパティを設定します
doc.DocumentProperties.Title = "Sample Document";
doc.DocumentProperties.Author = string.Format("Infragistics.{0}", SystemInformation.UserName);
Infragistics.Documents.Word.Font font = doc.CreateFont();
font.Bold = true;
font.Size = 15;
font.Underline = Underline.Double;
// 段落をドキュメントに追加します
Paragraph para1 = doc.ContentBlocks.AddParagraph();
para1.ContentRuns.AddTextRun("Sample Word Document with Hyperlinks,Images,Headers and Footers", font);
para1.ContentRuns.AddNewLine();
Paragraph para2 = doc.ContentBlocks.AddParagraph();
para2.ContentRuns.AddTextRun("Hyper link:  ");
// ハイパーリンクを追加します
para2.ContentRuns.AddHyperlink("http://www.infragistics.com", "Infragistics Inc.");
para2.ContentRuns.AddNewLine();
// 画像を取得します
Image img = Image.FromFile(@"..\..\Ballon_New_Year.jpg");
// 段落をドキュメントに追加します
Paragraph para3 = doc.ContentBlocks.AddParagraph();
para3.ContentRuns.AddTextRun("Anchored Picture: An Anchored picture or image is one that is anchored to a specific location within the document.Unlike an inline picture, which moves along with adjacent content, an Anchored Picture remains at a fixed location within the paragraph, with adjacent text flowing around it.");
// アンカー固定した画像を作成します
AnchoredPicture anchPic = doc.CreateAnchoredPicture(img);
// アンカー固定した画像の画像アウトライン プロパティを指定します
anchPic.AlternateTextDescription = "Word Image";
anchPic.Outline.Color = Color.Brown;
anchPic.Outline.Style = PictureOutlineStyle.Single;
anchPic.Outline.LineWidth = 1;
// アンカー固定した画像をパラグラフのアンカー セクションに追加します
para3.Anchors.AddAnchoredPicture(anchPic);
// 段落をドキュメントに追加します
Paragraph para4 = doc.ContentBlocks.AddParagraph();
para4.ContentRuns.AddTextRun("Inline Picture: An inline picture moves with the adjacent content");
// インライン画像を作成します
InlinePicture inlinePic = doc.CreateInlinePicture(img);
inlinePic.AlternateTextDescription = "Word Image";
// インライン画像をパラグラフのコンテンツ セクションに追加します
para4.ContentRuns.AddInlinePicture(inlinePic);
// 段落をドキュメントに追加します
Paragraph para5 = doc.ContentBlocks.AddParagraph();
// テキストをパラグラフに追加します
Section sec = doc.Sections.Add(para5);
// ヘッダー
Paragraph headerPara = sec.HeaderAllPages.ContentBlocks.AddParagraph();
// ヘッダー テキスト配置は、右に設定されます
headerPara.Properties.Alignment = ParagraphAlignment.Right;
// ヘッダーに表示するアンカー固定される画像を作成します
AnchoredPicture headeranchPic = doc.CreateAnchoredPicture(img);
// ヘッダーにアンカー固定された画像を表示します
headerPara.Anchors.AddAnchoredPicture(headeranchPic);
// ヘッダーにテキストを表示します
headerPara.ContentRuns.AddTextRun("This is a header");
// フッター
Paragraph footerPara = sec.FooterAllPages.ContentBlocks.AddParagraph();
// フッター テキスト配置は、右に設定されます
footerPara.Properties.Alignment = ParagraphAlignment.Right;
// フッターにテキストを表示します
footerPara.ContentRuns.AddTextRun("This is a footer");
// ページ番号をフッターに追加します
footerPara.ContentRuns.AddPageNumberField(PageNumberFieldFormat.Ordinal);
doc.Save(documentName);
----

*Visual Basic の場合:*

----
Imports Infragistics.Documents.Word
Dim documentName As String = "C:\TestWordDOMDoc.docx"
Dim doc As New Document()
' タイトル、著者などのドキュメント プロパティを設定します
doc.DocumentProperties.Title = "Sample Document"
doc.DocumentProperties.Author = String.Format("Infragistics.{0}", SystemInformation.UserName)
Dim font As Infragistics.Documents.Word.Font = doc.CreateFont()
font.Bold = True
font.Size = 15
font.Underline = Underline.[Double]
' 段落をドキュメントに追加します
Dim para1 As Paragraph = doc.ContentBlocks.AddParagraph()
para1.ContentRuns.AddTextRun("Sample Word Document with Hyperlinks,Images,Headers and Footers", font)
para1.ContentRuns.AddNewLine()
Dim para2 As Paragraph = doc.ContentBlocks.AddParagraph()
para2.ContentRuns.AddTextRun("Hyper link:  ")
' ハイパーリンクを追加します
para2.ContentRuns.AddHyperlink("http://www.infragistics.com", "Infragistics Inc.")
para2.ContentRuns.AddNewLine()
' 画像を取得します
Dim img As Image = Image.FromFile("..\..\Ballon_New_Year.jpg")
' 段落をドキュメントに追加します
Dim para3 As Paragraph = doc.ContentBlocks.AddParagraph()
para3.ContentRuns.AddTextRun("Anchored Picture: An Anchored picture or image is one that is anchored to a specific location within the document.Unlike an inline picture, which moves along with adjacent content, an Anchored Picture remains at a fixed location within the paragraph, with adjacent text flowing around it.")
' アンカー固定した画像を作成します
Dim anchPic As AnchoredPicture = doc.CreateAnchoredPicture(img)
' アンカー固定した画像の画像アウトライン プロパティを指定します
anchPic.AlternateTextDescription = "Word Image"
anchPic.Outline.Color = Color.Brown
anchPic.Outline.Style = PictureOutlineStyle.[Single]
anchPic.Outline.LineWidth = 1
' アンカー固定した画像をパラグラフのアンカー セクションに追加します
para3.Anchors.AddAnchoredPicture(anchPic)
' 段落をドキュメントに追加します
Dim para4 As Paragraph = doc.ContentBlocks.AddParagraph()
para4.ContentRuns.AddTextRun("Inline Picture: An inline picture moves with the adjacent content")
' インライン画像を作成します
Dim inlinePic As InlinePicture = doc.CreateInlinePicture(img)
inlinePic.AlternateTextDescription = "Word Image"
' インライン画像をパラグラフのコンテンツ セクションに追加します
para4.ContentRuns.AddInlinePicture(inlinePic)
' 段落をドキュメントに追加します
Dim para5 As Paragraph = doc.ContentBlocks.AddParagraph()
' テキストをパラグラフに追加します
Dim sec As Section = doc.Sections.Add(para5)
' ヘッダー
Dim headerPara As Paragraph = sec.HeaderAllPages.ContentBlocks.AddParagraph()
' ヘッダー テキスト配置は、右に設定されます
headerPara.Properties.Alignment = ParagraphAlignment.Right
' ヘッダーに表示するアンカー固定される画像を作成します
Dim headeranchPic As AnchoredPicture = doc.CreateAnchoredPicture(img)
' ヘッダーにアンカー固定された画像を表示します
headerPara.Anchors.AddAnchoredPicture(headeranchPic)
' ヘッダーにテキストを表示します
headerPara.ContentRuns.AddTextRun("This is a header")
' フッター
Dim footerPara As Paragraph = sec.FooterAllPages.ContentBlocks.AddParagraph()
' フッター テキスト配置は、右に設定されます
footerPara.Properties.Alignment = ParagraphAlignment.Right
' フッターにテキストを表示します
footerPara.ContentRuns.AddTextRun("This is a footer")
' ページ番号をフッターに追加します
footerPara.ContentRuns.AddPageNumberField(PageNumberFieldFormat.Ordinal)
doc.Save(documentName)
----

[[RelatedTopics]]
== 関連トピック

* link:word-create-a-word-document.html[Word 文書の作成]
* link:word-apply-formatting-to-word-document.html[書式設定を Word 文書に適用]
* link:word-add-table-to-word-document.html[テーブルを Word 文書に追加]
* link:word-add-images-to-word-document.html[画像を Word 文書に追加]
* link:word-headers-footers-and-page-numbers.html[ヘッダー、フッター、ページ番号]
* link:word-understanding-infragistics-word-library.html[Infragistics Word ライブラリの理解]